## Bim Coiffeur - Mani Matter\


4/4\
|C.......|....Am..|Dm......|....G7..|\
|C.......|....Am..|Dm......|G7......|\

Bim Coiffeur bin i gsässe vor em Spiegel, luege dry\
Und gseh dert drinn e Spiegel wo ar Wand isch vis-à-vis\
Und dert drin spieglet sech dr Spiegel da vor mir\
Und i däm Spiegel widerum dr Spiegel hindefür\

Und so geng wyter, s'isch gsy win e länge Korridor\
I däm my Chopf gwüss hundertfach vo hinden und vo vor\
Isch ufgreit gsy i eier Kolonne, z'hinderscht isch dr Chopf\
I ha ne nümme gchennt, so chly gsy win e Gufechnopf\

My Chopf, dä het sich dert ir Wyti, stellet öich das vor\
Verloren ir Unäntlechkeit vom länge Korridor\
I ha mi sälber hinde gseh verschwinde, ha das gseh\
Am heiterhälle Vormittag und wi we nüt wär gscheh\

Vor Chlupf han i mys Muul ufgscperrt, da sy im Korridor\
Grad hundert Müüler mit ufgange win e Männerchor\
E Männerchor us mir alei, es cheibe gspässigs Gfüel\
Es metaphysischs Grusle het mi packt im Coiffeurgstüel\

Letzte.Strophe:\
|C.......|....Am..|Dm......|....G7..|\
|C.......|....Am..|Dm..G7..|....C...| \

I ha d'Serviette vo mer grissen, ungschore sofort\
Das Coiffeurgschäft verla mit paar entschuldigende Wort\
Und wenn dir findet i sött e chly meh zum Coiffeur ga\
De chöit dir jitz verstah warum i da e Hemmig ha\

