## Der Traum vom Fliegen - Alexandra\
\
% Inro:\
% Am__|D___|Am__|D___|\
% Chorus:\
% Am___|D___|G___|C___|D___|G_Am_|____|\
% D___|G___|C___|D___|G_Am_|____|\
\
% F___|G___|C___|__G_|Am___|D_F_|\
% E___|F__G|\
\
Intro: Am D Am D\
\
Am        D\
An einem Baum\
G               C\
In dem Park der grossen Stadt\
D                          G     Am\
Hing unter tausenden Blättern ein Blatt\
                   D\
Sang der Nachtwind in den Bäumen\
G               C\
Wiegte sich das Blatt in Träumen\
D              G          Am\
Von der weiten herrlichen Welt\
\
Refr\
F              G              C   G\
Könnt ich nur einmal wie der Wind\
Am D F E\
Flie   gen\
F       G      C             \
Mit den Wolken übers Meer\
         E     C           \
Ach mein Leben gäb ich her\
           G  F  G\
Könnt ich Flie   gen\
              F Am  D\
Könnt ich Fliegen\
\
\
Am           D\
Bald kam der Herbst\
G                   C\
Gab dem Blatt sein schönstes Kleid\
D                   G            Am\
Doch es klagte den Wolken sein Leid:\
                   D\
"Bleiben muss ich und verblühen\
G                  C\
Könnt ich mit den Schwänen ziehen\
D               G             Am\
Dorthin wo der Sommer nie vergeht..."\
\
Refr\
F            G                      C\
Da rief der Herbstwind: "Du sollst fliegen! \
Am D F E      F\
Flie   gen!"\
       G        C                     \
Und er riss vom Baum das Blatt\
         E             D \
trieb es in die große Stadt\
         G C G\
ließ es flie gen, ließ es\
  F  Am    D \
Flie gen\
 \
Am           D\
Kurz war das Glück\
G             C\
Müde sank das Blatt hinab\
D                    G           Am\
Auf die Straße, sein regennasses Grab\
           D\
Schon am Ende seines Lebens\
G               C\
Rief das kleine Blatt vergebens\
D               G         Am\
Zu den stummen Häusern hinauf:\
F           C    G              C   E\
Könnt ich nur einmal noch im Wind\
Am D F  E\
Flie    gen!\
F        G      C\
Flög ich hin zu meinem Baum\
        E     C\
Und vergessen wär der Traum\
     G F  G\
Vom Flie  gen\
       F  Am\
Vom Flie  gen...\
\
