## The Shins - New Slang\
\
\
\
Intro: Am C F C G C Am G 2x C\
\
Am               C\
Gold teeth and a curse for this town \
F              \
Were all in my mouth\
     C                         Am   G\
Only I don't know how they got out, dear\
Am             C\
Turn me back into the pet \
F\
I was when we met\
C                          Am   G\
I was happier then with no mind set\
\
Chorus:\
G                      C\
And if you'd a took to me like\
  F                 G\
A gull takes to the wind\
                        C\
Well, I'd a jumped from my tree\
    F                     C\
And I'd a danced like the king of the eyesores\
F                                 G\
And the rest of our lives would'a fared well\
\
\
Am                 C\
New slang when you notice the stripes\
F\
The dirt in your fries\
     C\
Hope it's right when you die\
Am      G\
Old and bony\
Am                 C\
Dawn breaks like a bull through the hall\
F\
Never should'a called\
    C\
But my heads to the wall\
        Am  G\
And I'm lonely\
\
Chorus\
\
\
Am                C\
God speed all the baker's at dawn\
F\
May they all cut their thumbs\
    C\
And bleed into their buns \
           Am   G\
'Till they melt away\
\
\
G                     C    \
I'm looking in on the good life\
           F               G\
I might be doomed never to find\
                           C\
Without a trust or flaming fields \
         F       G\
Am I too dumb to refine?\
                       C\
And if you'd a took to me like \
     F                     C\
Well I'd a danced like the queen of the eyesores \
F                                 G\
And the rest of our lives would'a fared well\
\
Outro\
\
\
