## S'Zundhölzli - Mani Matter\
\
\
\
|C________|G7_______|Am_______|E________|\
|F________|C________|F______G7|C________|\
\
I han es Zündhölzli azündt\
Und das het e Flamme gäh\
Und i ha für d'Zigarette\
Welle Füür vom Hölzli näh\
Aber ds Hölzli isch dervo-\
Gspickt und uf e Teppich cho\
Und es hätt no fasch es Loch \
i Teppich gäh dervo\
\
Ja me weis was cha passiere\
We me nid ufpasst mit Füür\
Und für d'Gluet ar Zigarette\
Isch e Teppich doch de z'tüür\
Und vom Teppich hätt o Grus\
Chönne ds Füür i ds ganze Hus\
Und wär weis, was da nid alles \
no wär worde drus\
\
S'hätt e Brand gäh im Quartier\
Und s'hätti d'Füürwehr müesse cho\
Hätti ghornet i de Strasse\
Und dr Schluuch vom Wage gno\
Und sie hätte Wasser gsprützt\
Und das hätt de glych nüt gnützt\
Und die ganzi Stadt hätt brönnt, \
es hätt se nüt meh gschützt\
\
Und d'Lüt wären umegsprunge\
I dr Angscht um Hab und Guet\
Hätte gmeint s'heig eine Füür gleit\
Hätte ds Sturmgwehr gno ir Wuet\
Alls hätt brüelet: Wär isch tschuld?\
Ds ganze Land i eim Tumult\
Dass me gschosse hätt uf \
d'Bundesrät am Rednerpult\
\
D'UNO hätt interveniert\
Und d'UNO-Gägner sofort o\
Für ir Schwyz dr Fride z'rette\
Wäre beid mit Panzer cho\
S'hätt sech usdehnt natina\
Uf Europa, Afrika\
S'hätt e Wältchrieg gäh und \
d'Mönschheit wär jitz nümme da\
\
I han es Zündhölzli azündt\
Und das het e Flamme gäh\
Und i ha für d'Zigarette\
Welle Füür vom Hölzli näh\
Aber ds Hölzli isch dervo-\
Gspickt und uf e Teppich cho -\
Gottseidank dass i's vom \
Teppich wider furt ha gno\
\
\
