project:
  type: book

book:
  title: "Songs"
  author: "Nils Ratnaweera"
  downloads: pdf
  sidebar: 
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Selected Songs"
      chapters:
      - 01_Selected_Songs/i_will_follow_you_into_the_dark.md
      - 01_Selected_Songs/suzanne.md
      - 01_Selected_Songs/windows_in_paradise.md
      - 01_Selected_Songs/all_the_world_is_green.md
      - 01_Selected_Songs/dance_me_to_the_end_of_love.md
      - 01_Selected_Songs/build_me_up_buttercup.md
      - 01_Selected_Songs/hallelujah.md
      - 01_Selected_Songs/jar_of_hearts.md
      - 01_Selected_Songs/new_slang.md
      - 01_Selected_Songs/viva_la_vida.md
      - 01_Selected_Songs/wagon_wheel.md
      - 01_Selected_Songs/mad_world.md
    - part: "Guitar Classics"
      chapters:
      - 02_Classics/hurt.md
      - 02_Classics/where_have_all_the_flowers_gone.md
      - 02_Classics/ein_bett_im_kornfeld.md
      - 02_Classics/house_of_the_rising_sun.md
      - 02_Classics/sweet_home_alabama.md
      - 02_Classics/streets_of_london.md
      - 02_Classics/calafornia_dreaming.md
      - 02_Classics/morning_has_broken.md
      - 02_Classics/dust_in_the_wind.md
      - 02_Classics/blowing_in_the_wind.md
      - 02_Classics/wind_of_change.md
      - 02_Classics/boulevard_of_broken_dreams.md
      - 02_Classics/sound_of_silence.md
      - 02_Classics/lemon_tree.md
    - part: "Mundart & Deutsch"
      chapters:
      - 03_Mundart_und_Deutsch/heidi.md
      - 03_Mundart_und_Deutsch/s_zundhoelzli.md
      - 03_Mundart_und_Deutsch/nueni_tramm.md
      - 03_Mundart_und_Deutsch/sie_hoert_musik_nur_wenn_sie_laut_ist.md
      - 03_Mundart_und_Deutsch/dr_alpeflug.md
      - 03_Mundart_und_Deutsch/heute_hier_morgen_dort.md
      - 03_Mundart_und_Deutsch/arabisch.md
      - 03_Mundart_und_Deutsch/sag_mir_wo_die_blumen_sind.md
      - 03_Mundart_und_Deutsch/der_traum_vom_fliegen.md
      - 03_Mundart_und_Deutsch/bim_coiffeur.md
      - 03_Mundart_und_Deutsch/eskimo.md
      - 03_Mundart_und_Deutsch/hemmige.md
      - 03_Mundart_und_Deutsch/das_testament.md
      - 03_Mundart_und_Deutsch/kaspar.md
      - 03_Mundart_und_Deutsch/alls_wo_mir_id_finger_chunnt.md
      - 03_Mundart_und_Deutsch/so_kleine_haende.md
      - 03_Mundart_und_Deutsch/dr_wecker.md
    - part: "Weihnachtslieder"
      chapters:
      - 04_Weihnachten/oh_tannenbaum.md
      - 04_Weihnachten/in_der_weihnachtsbaeckerei.md
      - 04_Weihnachten/oh_come_all_ye_faithful.md
      - 04_Weihnachten/es_ist_fuer_uns_eine_zeit_angekommen.md
      - 04_Weihnachten/ihr_kinderleit_kommet.md
      - 04_Weihnachten/am_weihnachtsbaume_die_lichter_brennen.md
      - 04_Weihnachten/oh_du_froehliche.md
      - 04_Weihnachten/silent_night.md
      - 04_Weihnachten/suesser_die_glocken_nie_klingen.md
      - 04_Weihnachten/zu_bethlehem_geboren.md
      - 04_Weihnachten/stille_nacht.md
      - 04_Weihnachten/kling_gloecklein.md
      - 04_Weihnachten/leise_rieselt_der_schnee.md
      - 04_Weihnachten/kommet_ihr_hirten.md
      - 04_Weihnachten/marys_bornchild.md
      - 04_Weihnachten/oh_holy_night.md
      - 04_Weihnachten/gloria.md
      - 04_Weihnachten/the_first_noel.md
    - part: "Volkslieder"
      chapters: 
      - 05_Volkslieder/Guggisberg.md
      - 05_Volkslieder/im_Aargau.md
      - 05_Volkslieder/Beresinalied.md
      - 05_Volkslieder/de_blogeti_hansli.md
      - 05_Volkslieder/gang_ruef_de_bruune.md
      - 05_Volkslieder/ich_kenne_europas_zonen.md
      - 05_Volkslieder/bergvagabunden.md
      - 05_Volkslieder/lustig_ist_das_zigeunerleben.md
      - 05_Volkslieder/es_Burebuebli.md
      - 05_Volkslieder/alles_fahrt_ski.md
      - 05_Volkslieder/lueged_vo_Berge_u_Tal.md
      - 05_Volkslieder/vo_Luzern.md
    - part: "Kinderlieder"
      chapters: 
      - 06_Kinderlieder/isch_mer_alles_eis_ding.md
      - 06_Kinderlieder/Hippi_gspaengstli.md
      - 06_Kinderlieder/traaeumli.md
      - 06_Kinderlieder/min_vatter_isch_en_appizaeller.md
      - 06_Kinderlieder/ramseiers_wei_go_grase.md
      - 06_Kinderlieder/der_Mond.md
      - 06_Kinderlieder/vo_luzern_gege_weggis.md
      - 06_Kinderlieder/vogellisi.md
      - 06_Kinderlieder/det_aenet_am_bergli.md


format:
  pdf: 
    documentclass: scrbook
    geometry:
      - left=10mm
      - top=10mm
      - right=10mm
      - bottom=10mm
    keep-tex: true
    include-before-body: titlepage.tex
    include-in-header: preamble.tex
    mainfont: FreeMono
    cover-image: misc/title.png
  html:
    css: style.css
    theme: darkly
    
from: markdown+hard_line_breaks-smart
# extension "hard_line_breaks" interprets single line breaks as hard line breaks
# extension "smart" replaces two -- as an emdash, which is not good for tabs