--- 
title: ""
pagetitle: "Songs"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, dev.args=list(bg = "transparent"))
```

```{r, results="asis"}
output <- knitr::opts_knit$get("rmarkdown.pandoc.to")# html / latex / docx

if(output == "html"){
  pander::pandoc.header("Songs {-}",1)
  pander::pandoc.image("misc/title.png")
}

```

A collection of hand picked songs. This book is hosted as an online version on https://ratnanil.github.io/Songs/ and includes pdf / epub versions (click on the download symbol). Edits and feedback can be made via the [github repo](https://github.com/ratnanil/songs). The current version was rendered on `r Sys.time()`. 



```{r, include=FALSE}
file.create("docs/.nojekyll")

library(tabr)





# A wrapper around tabr::plot_chord() which allows multiple chords and styles them in my specific way (4 columns, transparent background etc.)
plot_chords <- function(chords){
  # Get the maximum fret-delta of all chords
  delta_max <- map_int(chords,function(x){
    v <- suppressWarnings(as.integer(str_split(x,"",simplify = TRUE)))
    max(v,na.rm = TRUE)-min(v, na.rm = TRUE)
  }) %>%
    max()
  
  # Make a list of all chord plots
  plots <- imap(chords,function(x,y){
    v <- min(suppressWarnings(as.integer(str_split(x,"",simplify = TRUE))),na.rm = TRUE)
    
    plot_chord(x,
               labels = NULL,
               fret_range = c(v,v+delta_max), # so that all chords span the same nr of frets
               point_size = 4,
               label_size = 3) + 
      labs(tag = y) +
      theme(
        panel.background = element_rect(fill = "transparent"), # The theme 
        plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      )
    })
  chordnames <- map(chords, ~.x[2])
  plot_grid(plotlist = plots,ncol = 4)
}
```


```{r}


```


