---
title: Der Mond ist aufgegangen
artist: Matthias Claudius
year: 1779
source: https://www.youtube.com/watch?v=hvjZt9T3Ljk
capo: 2
time: 8/8
---

C   G7   F C G   C        F C  G7  C        F C 
---|--------|--------|--------|--------|--------|





C  (G7)   C   F    (C)     G7    C
Der Mond ist auf - ge  - gan - gen. 
            F    (C)    G7       C
Die goldnen Sternlein pran  -  gen 
   C      F    (C)   G
am Himmel hell und klar. 
C   (G7)   C      F    (C)   G7   C
Der Wald steht schwarz und schweiget
            F     (C)   G7       C
und aus den Wie - sen stei  -  get 
    C     F      (C)   G7    C
der weiße Ne  -  bel wunderbar. 
 
C  (G7)   C   F   (C)   G7    C
Wie ist  die Welt so  stil - le.
            F    (C)   G7      C
Und aus der Dämm'rung Hül  -  le 
   C         F  (C)  G
so traulich und so hold.
C  (G7)   C     F    (C)  G7   C
Als ei  - ne  stil - le  Kam - mer, 
            F    (C)  G7     C
wo ihr des Ta  - ges Jam  - mer 
    C        F  (C)    G7     C
verschlafen und ver - gessen sollt. 
 
C   (G7)  C   F    (C)  G7    C
Seht ihr den Mond dort ste  - hen. 
            F  (C) G7     C
Er ist nur halb zu se  - hen 
   C           F  (C)   G
und ist doch rund und schön. 
C  (G7)  C   F     (C) G7     C
So sind wohl man - che Sa  - chen, 
            F   (C)   G7     C
die wir getrost ver - la  - chen, 
    C       F   (C)    G7      C
weil unsre Au - gen sie nicht sehn. 
 
C   (G7) C  F  (C) G7  C
Wir stolze Menschenkinder
           F (C) G7 C
Sind eitel arme Sünder
   C        F   (C)   G
Und wissen gar nicht viel;
C   (G7)  C   F (C) G7 C
Wir spinnen Luftgespinste
            F (C) G7  C
Und suchen viele Künste
    C       F (C)    G7     C
Und kommen weiter von dem Ziel.
 
C     (G7) C    F   (C)   G7  C
Gott, laß  dein Heil uns schauen,
               F  (C)    G7  C
Auf nichts Vergänglichs trauen,
   C         F  (C)   G
Nicht Eitelkeit uns freun!
C   (G7) C  F (C) G7  C
Laß uns einfältig werden
             F   (C) G7 C
Und vor dir hier auf Erden
    C       F    (C)    G7      C
Wie Kinder fromm und fröhlich sein!
 
C      (G7) C   F (C)  G7 C
Wollst endlich sonder Grämen
            F   (C)  G7 C
Aus dieser Welt uns nehmen
   C         F  (C)  G
Durch einen sanften Tod!
C    (G7) C   F  (C) G7 C
Und, wenn du uns genommen,
            F (C)  G7 C
Laß uns in Himmel kommen,
    C     F   (C)   G7    C
Du unser Herr und unser Gott!
 
C  (G7)  C    F    (C)  G7 C
So legt euch denn, ihr Brüder,
           F (C) G7 C
In Gottes Namen nieder;
   C         F (C)  G
Kalt ist der Abendhauch.
C  (G7)   C    F    (C)  G7  C
Verschon uns, Gott! mit Strafen,
            F (C)    G7 C
Und laß uns ruhig schlafen!
    C       F  (C)    G7     C
Und unsern kranken Nachbar auch!
