---
title: Blowing in the Wind
artist: Bob Dylan
---

[C]       [F]        [C]      [Am] 
How many roads must a man walk down, 
  [C]        [F]  [G]-[G7]
before you call him a man?
[C]     [F]          [C]       [Am] 
How many seas must a white dove sail, 
  [C]        [F]        [G]-[G7]
before she sleeps in the sand?
[C]     [F]               [C]  [Am]
How many times must the cannonballs fly, 
  [C]           [F]    [G]
before they're forever banned?
      [F]       [G]      C              Am            
The answer my friend, is blowing in the wind.
      [F]       [G]         [C]
The answer is blowing in the wind.

How many years must a mountain exist, 
before it is washed to the sea?
How many years can some people exist, 
before they're allowed to be free? 
How many times can a man turn his head, 
and pretend that he just doesn't see?
The answer my friend, is blowing in the wind.
The answer is blowing in the wind.

How many times must a man look up, 
before he can see the sky?
How many ears must one man have, 
before he can hear people cry?
How many deaths will it take 'till he knows, 
that too many people have Died?
The answer my friend, is blowing in the wind.
The answer is blowing in the wind.


