---
title: Boulevard of Broken Dreams
artist: Green Day
---

[Em]     [G]          
I walk a lonely road, 
  [D]            [A]           [Em]
the only one that I have ever known
           [G]           
Don't know where it goes,
[D]              [A]             [Em]
but it's home to me and I walk alone

:::{.song-grid}
Em··|G···|D···|A···| 
:::

I walk this empty street, 
on the boulevard of broken dreams
Where the city sleeps, 
and I'm the only one and I walk alone


[Em][G][D]          [A]         [Em]
.........I walk alone, I walk alone.
[Em][G][D]          [A]
.........I walk alone, I walk a....


:::{.chorus}
[C]    [G]          [D]            [Em]
    My shadow's the only one that walks beside me
[C]     [G]     [D]             [Em]
    My shallow heart's the only thing that's beating
[C]     [G]     [D]               [Em]
    Sometimes I wish someone out there will find me
[C]      [G]    [B7]
    Till then I walk alone
:::


[Em]  [G]   [D]     [A]
Ah-Ah Ah-Ah Ah-Ah   Ahhh-Ah
    [Em] [G]   [D]     [A]
haaa-ah  Ah-Ah Ah-Ah   Ah-Ah


I'm walking down the line
That divides me somewhere in my mind
On the border line of the edge
And where I walk alone

:::{.song-grid}
Em G  D  A
:::

Read between the lines
What's fucked up and everything's all right
Check my vital signs, to know I'm still alive
And I walk alone


I walk alone, I walk alone.
I walk alone, I walk a....


*play chorus*


Ah-Ah Ah-Ah Ah-Ah   Ahhh-Ah
haaa-ah  Ah-Ah Ah-Ah  
I walk alone, I walk a...


:::{.song-grid}
 C G  D  Em 
 C G  D  Em 
 C G  D  Em 
 C G  B  B7 
:::


I walk this empty street, 
on the boulevard of broken dreams
Where the city sleeps, 
and I'm the only one and I walk a...


*play chorus*


