---
title: Ein Bett im Kornfeld
artist: Jürgen Drews

---

[D]
Sommerabend über blühendem Land.
Schon seit Mittag stand ich am 
Straßenrand.
           [A]
Bei jedem Wagen, der vorüber fuhr,
            [D]
hob ich den Daumen.
auf einem Fahrrad kam da ein 
Mädchen her.
Und sie sagte: "Ich bedaure dich sehr."
          [A]                                         [D]
Doch ich lachte und sprach: "Ich brauch keine weichen Daunen"

:::{.song-chorus}
             [G]
Ein Bett im Kornfeld,
Das ist immer frei, denn es ist
[D]
Sommer, und was ist schon dabei.
            [A]
Die Grillen singen und es duftet 
                   [D]
nach Heu, wenn ich träume.
             [G]
Ein Bett im Kornfeld, zwischen 
Blumen und Stroh,
         [D]
Und die Sterne leuchten mir sowieso
             [A]
Ein Bett im Kornfeld mach ich mir 
               [D]
irgendwo ganz alleine.
:::

[D]
Etwas später lag ihr Fahrrad im 
Gras, Und so kam es, dass sie die 
Zeit vergass,
         [A]
Mit der Gitarre hab ich ihr erzählt
           [D]
Von meinem Leben.
Auf einmal rief sie
"Es ist höchste Zeit, Schon ist es 
dunkel und mein Weg ist noch Weit"
          [A]
Doch ich lachte und sprach:
                           [D]
"Ich hab dir noch viel zu geben".

{chorus}


