---
title: Lemon Tree
artist: Fools Garden
year: 1996
tempo: 115 bpm
capo: 1

---

:::{.song-grid}
Em··|Bm··|Em··|Bm··|
Am··|Bm··|Em··|Bm·E|
:::

[Em]             [Bm]
I'm Sitting Here In a Boring Room
[Em]                          [Bm]
It's Just Another Rainy Sunday Afternoon
[Em]                     [Bm]
I'm Wasting My Time I Got Nothing To Do
[Em]                  [Bm]
I'm Hanging Around I'm Waiting For You
   [Am]                 [Bm]    [Em] [Bm][Em]
But Nothing Ever Happens - And I Wonder

I'm Driving Around In My Car
I'm Driving Too Fast I'm Driving Too Far
I'd Like To Change My Point Of View
I Feel So Lonely I'm Waiting For You
But Nothing Ever Happens - And I Wonder

:::{.chorus}
[G]           [D]
I Wonder How I Wonder Why
[Em]                           [Bm]
Yesterday You Told Me 'bout The Blue Blue Sky
[C]               [D]                  [G]       [D]
And All That I Can See Is Just A Yellow Lemon-tree
[G]                [D]
I'm Turning My Head Up And Down
[Em]                                [Bm]
 I'm Turning Turning Turning Turning Turning Around
[C]               [A]                  [D]
And All That I Can See Is Just another Lemon-tree
:::


<!-- bridge -->
Em Bm Em Bm Am Bm Em 
dadada....

I'm Sitting Here I Miss The Power
I'd Like To Go Out Taking a Shower
But There's a Heavy Cloud Inside My Head
I Feel So Tired Put Myself Into Bed
Where Nothing Ever Happens - And I Wonder

[B]         [Em]
Isolation - Is Not Good For Me
[D]        [G]              [B]
Isolation - I Don't Want To Sit On a Lemon-tree

I'm Steppin' Around In a Desert Of Joy
Baby Anyhow I'll Get Another Toy
And Everything Will Happen - And You'll Wonder

*play chorus twice*

[C]               [D]
And All That I Can See
[C]               [D]
And All That I Can See
[C]               [D]
And All That I Can See
                [G]
Is Just a Yellow Lemon-tree.


