---
title: Alles fahrt Ski
source: https://www.brauchtumschweiz.ch/volkslieder-mundart/alles-fahrt-ski

---

Alles fahrt Schi, alles fahrt Schi, Schi fahrt die ganzi Nation. 
Alles fahrt Schi, alles fahrt Schi, d’Mamme, der Bappe, der Sohn. 
Es git halt nüt Schöners, juhe, juhe, als Sunneschy, Bärge und Schnee.

’s Grittli mit Keilhose, satte, puderet, gschminkt, parfümiert, 
stoht wie ne Kueh uff de Latte, zmitts uff der Piste und friert.

D’Hänsche hett’s Grittli verlore, iskalt sind d’Finger vom Schnee; 
‘s jommeret halber verfrore: "Wie schön wär’s bim Feif-o-Glogg-Tee!"

D’Schilehrer flott demonstriere, Slalom und Sprunglauf im Schuss. 
Gli wills der Meier probiere, fliegt wiene Mählsagg uff d’Nuss. 
Springe uff d’Syte macht Freude; stolz seit der Lehrer "s’isch guet!" 
Druff meint der Meier bescheide: "Der Sytesprung liegt mir im Bluet!"

D’Sässelilift bringe d’Pärli uffe ins Bärgrestaurant, 
dört sitzt der Köbi und ‘s Clärli, fröhlig im Liegstuel binand. 
‘s Clärli tuet salbe und schmiere, ‘s liegt an der Sunne ganz schlapp; 
schüch seit’s mit zündroter Bire: "Ich fahr mit em Bähnli durab!"

Zobe bim Tanz seit der Dölfi: "Samba git Vorlag in d’Bei!" 
‘s Miggi macht mit bis am zwölfi, ‘s gfallt em, ‘s möcht gar nümme hei. 
Schnäll nimmt’s en Schluck vo sym Schnäpsli, git dänn im Dölfi der Räscht. 
Plötzlig seit es zu sym Schätzli: "Ich blib morn der ganz Tag im Näscht!"
