---
title: Es Burebüebli
artist: vo Bern
source: https://als.wikipedia.org/wiki/Text:Volkslieder/Es_Bureb%C3%BCebli
---


Strophe: C G7 C G7 C F C G7 C
Refrain: C G7 C G7 C F C G7 C

Es Burebüebli mahn i nid, 
das gseht me mir wohl a, juhe,
Es Burebüebli mahn i nid, 
das gseht me mir wohl a
Fidiri, fidira, fidirallala, 
fidirallala, la rallala,
Es Burebüebli mahn i nid, 
das gseht me mir wohl a.

S muess eine sy gar hübsch und fyn, 
darf keiner Fähler ha, juhe,
S muess eine sy gar hübsch und fyn, 
darf keiner Fähler ha,
Fidiri, fidira, fidirallala, 
fidirallala, la rallala,
Fidiri, fidira, fidirallala, 
darf keiner Fähler ha.

Und Herrebüebli git's ja nid, 
wo keiner Fähler hei, juhe,
Und Herrebüebli git's ja nid, 
wo keiner Fähler hei,
Fidiri, fidira, fidirallala, 
fidirallala, la rallala,
Und Herrebüebli git's ja nid,
wo keiner Fähler hei.

Drum bliben i ledig bis in Tod, 
so het die Lieb es Änd, juhe,
Drum bliben i ledig bis in den Tod, 
so het die Lieb es Änd,
Fidiri, fidira, fidirallala, 
fidirallala, la rallala,
Drum bliben i ledig bis in den Tod, 
so het die Lieb es Änd.
