---
title: Lied des Zigeuners
artist: Jean Portier und Dietmar Janz
source: https://angerweit.tikon.ch/lieder/jugendbewegung/europaszonen.pdf

---


    Em
ich kenne Europas Zonen
vom Ural bis westlich Paris.
H7                      Em
Die Händel der großen Nationen
    H7                Em
der Klassen und Konfessionen
                    H7          Em   
sind für mich nur großer Beschiss
    G          G/h        C        G
Ich bin ein gemeiner, zerlumpter Zigeuner
    G                       D    A
ich habe keine Heimat, kein Geld
         C              D7     G
nur mein Pferd und die sonnige Welt

Ich streifte von Hollands Grachten
bis weit in das russische Reich.
Ich konnte die Menschen betrachten
und lernte sie gründlich verachten
denn im Grunde sind alle gleich:
Sie schreien „Gemeiner, zerlumpter Zigeuner!“
sie messen unsern Wert nur nach Geld
mich, mein Pferd und die sonnige Welt

Sie fragten nach meinen Papieren
ich streckte die Zunge heraus.
Sie wollten mich nummerieren
in Büchern und Listen führen,
doch ich lachte sie einfach aus.
Ich bin ein gemeiner, zerlumpter Zigeuner,
doch Freiheit ist besser als Geld
für mich, mein Pferd und die Welt

