---
title: All the World is Green
artist: Tom Waits

---

[Bm]           [Em]  [A7]            [D]
I fell into the ocean  and you became my wife
[G7]                                        [Bm]
 I risked it all against the sea to have a better life
          [Em]             [A7]         [D]
Marie you are the wild blue sky, men do foolish things
[G7]                                      [Bm]
 You turn kings into beggars and beggars into kings

:::{.chorus}
  [G]                  [D] 
Pretend that you owe me nothing      
   [A7]             [D]
and all the world is green
[G]                   [D]        
 We can bring back the old days again     
    [A7]             [D]
when all the world is green
:::

The face forgives the mirror
The worm forgives the plow
The questions begs the answer
Can you forgive me somehow?

Maybe when our story's over
We'll go where it's always spring
The band is playing our song again
And all the world is green [Play Chorus]

The moon is yellow silver
On the things that summer brings
It's a love you'd kill for
And all the world is green

He's balancing a diamond
On a blade of grass
The dew will settle on our graves
When all the world is green

{Comment: Play chorus, solo, repeat last verse}

