---
title: I will follow you into the Dark
artist: Death Cab for Cutie
capo: 5

---

[C]
Love of mine
                [Am] (D root note)
Someday you will die
                     [F]
But I will be close behind
          [C]                [G]
I will follow, you into the dark

No blinding light
Or tunnels to gates of white
Just our hands clasped so tight
Waiting for, the hint of a spark 

:::{.chorus}
  [Am]               [C]     
If heaven and hell decide,      
          [F]         [C]G
that they both are satisfied
[Am]            [C]                G(bar)
Illuminate the "no's", on their vacancy signs
[Am]                     [C]
If there's no one beside you,
          [E]    [Am]G
when your soul embarks
Bb                 Bbm           [F](C root note)
Then I will follow you into the dark
:::

Catholic school
As vicious as roman rule
I got my knuckles bruised 
By a lady in black
     
And I held my tongue 
as she told me "son, fear is the heart of love." 
So I never went back

*play chorus*

You and me, have seen everything to see
From Bangkok to Calgary  
And the soles of your shoes
 
Are all worn down, the time for sleep is now
But it's nothing to cry about  
Because we'll hold each other soon
[Am]                 Fm    Fm
in the blackest of rooms 

[Am]                [C]    
If heaven and hell decide, 
          [F]          [C]G
that they both are satisfied
[Am]            [C]                G(bar)
Illuminate the "no's", on their vacancy signs
[Am]                     [C]            [E]    [Am]G
If there's no one beside you, when your soul embarks
[F]               Fm           [C]   
Then I will follow you into the dark

:::{.tab}
E---------------------|
B---1---1--------1----|
G---2---2--------2----|
D---0---0--------2----|
A---3---2----0---0----|
E---------------------|
:::

[F]               Fm           [C]   
Then I will follow you into the dark


