---
title: New Slang
artist: The Shins

---

:::{.song-grid}
Am C F C G C Am G x4
 C 
:::

[Am]            [C]            [F]
Gold teeth and a curse for this town
[C]           [G]
Were all in my mouth
    [C]          [F]          [Am] [G]
Only I don't know how they got out, dear
[Am]          [C]    [F]
Turn me back into the pet
[C]          [G]
I was when we met
[C]          [F]          [Am] [G]
I was happier then with no mind set

:::{.song-chorus}
[G]                   [C]
And if you'd a took to me like
 [F]  [C]          [G]
A gull takes to the wind
           [G]         [C]
Well, I'd a jumped from my tree
   [F]   [C]             [F]         [C]
And I'd a danced like the king of the eyesores
[F]                [C]           [G]
And the rest of our lives would'a fared well
:::

[Am]              [C]        [F]
New slang when you notice the stripes
[C]             [G]
The dirt in your fries
    [C]                 [F]
Hope it's right when you die
       [Am][G]
Old and bo..ny
[Am]              [C]              [F]
Dawn breaks like a bull through the hall
[C]           [G]
Never should'a called
   [C]             [F]
But my heads to the wall
       [Am][G]
And I'm lonely

{chorus}

[Am]             [C]        [F]
God speed all the baker's at dawn
            [C]       [G]
May they all cut their thumbs
   [C]              [F]
And bleed into their buns
          [Am] [G]
'Till they melt away

:::{song-chorus}
[G]                   [C]
I'm looking in on the good life
          [F]    [C]      [G]
I might be doomed never to find
                          [C]
Without a trust or flaming fields
    [F] [C]     [G]
[Am] too dumb to refine?
                      [C]
And if you'd a took to me like
    [F]   [C]             [F]          [C]
Well I'd a danced like the queen of the eyesores
[F]                [C]           [G]
And the rest of our lives would'a fared well
:::
