---
title: Alls wo mir id finger chunnt
artist: Mani Matter
time: 2/4

---


:::{.song-grid}
|Am______|Dm______|G7______|C_______|
|Dm______|Am______|E7______|________|
|Am______|Dm______|G7______|C_______|
|Dm______|Am______|E_______|Am______| 
:::

Am tag won i uf d'Wält bi cho, si hei mers speter gseit
Da het my Mueter grad deheim es Suppegschir verheit
Und sider ischs mys herte Los bis a mys Läbesänd
Alls wo mir id Finger chunnt verbricht mer i de Händ

I cha mer Müe gäh wi i wott, es nützt mer alles nüt
Was geschter no isch ganz gsy isch i tuusig Bitze hütt
Die Schärbehüüfe won i hinderla, die rede Bänd
Alls wo mir id Finger chunnt verbricht mer i de Händ

I han emal es Meitschi gchennt, s'isch truurig aber wahr
Es Meitschi ganz us Porzelan mit rabeschwarze Haar
Uf einisch isch es zue mer cho, het gseit: Jitz isch es z'Änd
Alls wo mir id Finger chunnt verbricht mer i de Händ

Und won i's du zum letschten Abschid a mys Härz ha trückt
Da han i's z'fescht umarmet und vor Liebi grad erstickt
I has nid äxtra gmacht, dir chöit mers gloube, Sackermänt
Alls wo mir id Finger chunnt verbricht mer i de Händ

Si hei mi vor e Richter gstellt und hei mi geschter ghänkt
Und won i scho bi ghanget, da uf ds Mal, wär hätt das tänkt
Da het dr Strick la gah im allerletschtischte Momänt
Alls wo mir id Finger chunnt verbricht mer i de Händ

Und sider blyben i Vagant und mache lieber nüt
Dir wärdet das begryffe, drum syt güetig, liebi Lüt
Und gryffet ou i ds Portmonee und gäht e mildi Spänd
Alls wo mir id Finger chunnt verbricht mer i de Händ
