---
title: Testament
artist: Sarah Lesch

---


    [Em]
Auch du warst mal ein Kind und auch ich war mal klein
        [D]                [Em]
Und auch uns ham sie was erzählt
        [Em]
Und dann macht man das alles und versucht so zu sein
         [D]                     [Em]
Und dann merkt man das einem was fehlt
            [Em]
Und dann verlernt man, sich richtig zu spüren
         [D]                          [Em]
Und man flüchtet sich in Kunst oder Konsum
    [Em]
Und während ihr fleißig Pläne macht,
[D]                    [Em]
Lachen die Götter sich krumm

           [H7]                [Em]
Lasst eure Kinder mal was dazu sagen
[H7]              [Em]
Hört ihnen richtig zu.
    [H7]                     [Em]
Die spürn sich noch, die ham Feeling für die Welt
         [Am]              [H7]
Die sind klüger als ich und du

    [C]                  [G]
Und denkt dran bevor ihr antwortet:
        [H7]                [Em]
Ihr seid auch nur verletzte Kinder.
   [C]                     [G]
[Am]nde gibt’s wieder ganz neue Symptome,
   [H7]            [Em]
und ihr wart die Erfinder
         [C]                       [G]
Und dann sagt ihnen wieder, wie es richtig geht
       [H7]          [Em]
„Werd erwachsen“ und „bist du naiv“
        [C]                     [G]
Predigt Formeln, lasst alles in Hefte schreiben,
    [Em]                 [D]
Die Götter lachen sich schief
[Em]
Achtet auf Schönschrift und Lehrpläne
  [D]                       [Em]
Und dass sie die Bleistifte spitzen
[Em]              
Zeigt ihnen Bilder von Eichenblättern 
             [D]               [Em]
Während sie drinnen an Tischen sitzen
        [Em]
Und dann ackern und büffeln und wieder auskotzen
       [D]
Und am Nachmittag RTL 2
  [Em]
[Am]ochenende geht’s was Schönes kaufen, 
[D]                       [Em]
fertig ist der Einheitsbrei
    [Em]
Und jeder der sich nicht anpasst
    [D]                  [Em]
Wird zum Problemkind erklärt
   [Em]
Und jede, die zu lebhaft ist
          [Am]                    [H7]
Kriegt ‘ne Pille damit sie nicht stört

     [H7]                  [Em]
Und damit betrügt ihr euch selber denn
[H7]               [Em]
Kein Kind ist ein Problem
             [H7]                 [Em]
Und all die Freigeister, all die Schulschwänzer
       [Am]            [H7]
Nur Symptomträger im System


              [C]            [G]               
Doch bedenkt wenn ihr so hart urteilt:
        [H7]                [Em]
Ihr seid auch nur gefangene Geister
   [C]               [G]
Der Unmut wird immer lauter 
        [H7]                 [Em]
Und die Lehrer schreien sich heiser
[C]                                [G]
Empört euch, dass Hänschen nicht ist, was er sein soll,
       [H7]                [Em] 
Sondern nur, wer er nunmal ist
    [C]                 [G]
Die Götter pullern sich ein vor Lachen
   [Em]                     [D]
Und ihr denkt, dass ihr was wisst

 
[Em]                    .            .  
Und wenn Hänschen dann Hans ist Der eigene Kinder hat, 
[D]             [Em]
denen er was erzählt 
    [Em]             .         .
Dann merkt Hans und Kunz, und ihr vielleicht auch,
     [D]              [Em]
Dass wieder irgendwas fehlt 
     [Em]                        .
Ihr habt Wünsche und Träume und rennt damit ständig 
[D]          [Em]
an imaginäre Wände
          [Em]
Und jeder Wunsch den ihr euch erfüllt 
        [D]              [Em]
Der ist dann halt auch zu Ende
    [Em]                     .
Geht ihr nur Malochen für erfundene Zahlen
     [D]                     [Em]
Und wartet, bis die Burnouts kommen
  [Em]                  .
Schmeißt euer Geld für Plastik raus
        [D]              [Em]
Um ein kleines Glück zu bekommen
   [Em]           .          .
Das Beste aus Cerealien und Milch
        [D]                   [Em]
Noch ‘n Carport und noch ‘n Kredit
       [Em]
|: Und alle finden‘s scheiße        
      [D]            [Em]
 aber alle machen sie mit :|         

    [H7]                    [Em]
Ihr klugscheißert und kauft trotzdem
        [H7]                      [Em]
Und die Werbung verkauft euch für dumm
         [H7]                [Em]
Und dann sitzt ihr vor neuen Flachbildfernsehern
    [H7]             [Em]
Und meckert auf den Konsum
          [H7]                    [Em]   
Wenn ihr das Welt nennt, bin ich gern weltfremd
    [H7]               [Em]
Die Götter lachen sich krumm
         [H7]                    [Em]
Wenn ihr das Welt nennt, bin ich gern weltfremd
   [Am]                [H7]
Die Götter lachen sich krumm


     [C]               [G]
Ihr Traumverkäufer, Symptomdesigner
[H7]                    [Em]
Merkt ihr noch, was passiert? 
[C]                           [G]
Wer hat euch das Land und das Wasser geschenkt, 
        [H7]          [Em]
Das ihr jetzt privatisiert
     [C]                      [G]
Ihr Heuchler, ihr Lügner, ihr Rattenfänger 
    [H7]         [Em]
Ihr Wertpapierverkäufer
    [C]                  [G]
Man hat euch Geist und Gefühl gegeben 
    [H7]                 [Em]
Und doch seid ihr nur Mitläufer 
     [C]                [G]
Ihr großen, vernarbten, hilflosen Riesen 
    [H7]               [Em]
Ihr wart doch auch mal klein
    [C]                    [G]
Und jemand hat euch mit Schweigen gestraft 
    [H7]               [Em]
Und ließ euch darin allein 
          [C]                    [G]
Und jetzt hört ihr nicht nur die Götter nicht lachen 
    [H7]                           [Em]
Ihr hört auch ihr die Kinder nicht weinen
    [C]                   [G]
Und sagt ihnen weiter, es würde nicht wehtun
[H7]            [Em]
  Ohne es so zu meinen
      [C]             [G]
Macht ihr ruhig Pläne, ich steh am Rand 
    [H7]                          [Em]
Ich sehe euch und ich bin nicht allein 
       [C]                      [G]
Hinter mir stehen mehr und mehr Weltfremde 
    [H7]                 [Em]
Die passen auch nicht hinein 

          [C]                     [G]
Und jetzt wartet nicht auf ein versöhnliches Ende 
 [H7]                    [Em]
Den Gefallen tu ich euch nicht 
    [C]                   [G]
Kein Augenzwinkern, keine milde Pointe,
        [H7]               [Em]
Die das Unwohlsein wieder bricht
      [C]                    [G]
Irgendwann werden die Götter nicht mehr lachen 
   [H7]                           [Em]
Und falls es mich dann nicht mehr gibt 
       [C]                         [G]
Hinterlass ich ein Kind, das sich selbst gehört
[H7]                         [Em]
   Und dies unhandliche Lied
   


