---
title: Der Traum vom Fliegen
artist: Alexandra
year: 1968
capo: 0

---
{temp: 8/8}

 <!--Intro-->

:::{.song-grid}
Am····|D·····|Am····|D·····|
:::

<!--Verse-->
:::{.song-grid}
Am····|D·····|G·····|C·····|
D·····|G··A··|Am····|···Dm·|
···G··|···C··|···D··|···G··|
Am····|······|
:::

<!--Chorus-->
:::{.song-grid}
F·····|G·····|C·····|···D··|
Am····|G··F··|······|E·····|
F·····|···C··|······|···D··|
G·····|······|······|Am····|
:::


An einem Baum
In dem Park der grossen Stadt
Hing unter tausenden Blättern ein Blatt
Sang der Nachtwind in den Bäumen
Wiegte sich das Blatt in Träumen
Von der weiten herrlichen Welt

:::{.chorus}
Könnt ich nur einmal wie der Wind
Flie   gen
Mit den Wolken übers Meer
Ach mein Leben gäb ich her
Könnt ich Flie-gen
Könnt ich Fliegen
:::

Bald kam der Herbst
Gab dem Blatt sein schönstes Kleid
Doch es klagte den Wolken sein Leid:
"Bleiben muss ich und verblühen
Könnt ich mit den Schwänen ziehen
Dorthin wo der Sommer nie vergeht..."

Refr
Da rief der Herbstwind: "Du sollst fliegen! 
Flie   gen!"
Und er riss vom Baum das Blatt
trieb es in die große Stadt
ließ es flie gen, ließ es
Flie gen
 
Kurz war das Glück
Müde sank das Blatt hinab
Auf die Straße, sein regennasses Grab
Schon am Ende seines Lebens
Rief das kleine Blatt vergebens
Zu den stummen Häusern hinauf:
Könnt ich nur einmal noch im Wind
Flie    gen!
Flög ich hin zu meinem Baum
Und vergessen wär der Traum
Vom Flie-gen
Vom Flie-gen...

