---
title: Heute hier morgen Dort
artist: Hannes Wader

---

     [G]                
Heute hier, morgen dort 
        [C]        [G]
bin kaum da muß ich fort
                     [Em]    [D]
hab mich niemals des wegen beklagt
       [G]               
hab es selbst so gewählt
        [C]      [G]
nie die Jahre gezählt 
         [Em]       [D]     [G]
nie nach gestern und morgen gefragt

:::{.song-chorus}
          [D]              
Manchmal träume ich schwer 
        [C]          [G]
und dann denk` ich es wär
         [D]            
Zeit zu bleiben und nun 
        [C]       [G]
was ganz andres zu tun
                        
So vergeht Jahr um Jahr 
   [C]            [G]
und ist mir längst klar
          [Em]     
daß nichts bleibt, 
          [D]           [G]
daß nichts bleibt wie es war.

:::

       [G]                
Daß man mich kaum vermißt 
          [C]      [G]
schon nach Tagen vergißt
                      [Em]      [D]
wenn ich längst wieder anders wo bin
         [G]                 
stört und kümmert mich nicht
          [C]          [G]
vielleicht bleibt mein Gesicht 
        [Em]     [D]        [G]
doch dem ein oder andern im Sinn

{chorus}

          [G]          
Fragt mich einer warum 
      [C]             [G]
ich so bin bleib ich stumm
                  [Em]           [D]
denn die Antwort darauf fällt mir schwer
        [G]               
denn was neu ist wird alt
        [C]         [G]
und was gestern noch galt 
            [Em]        [D]         [G]
stimmt schon heut oder morgen nicht mehr.

           [D]             
Manchmal träume ich schwer 
         [C]          [G]
und dann denk ich es wär
         [D]            
Zeit zu bleiben und nun 
        [C]       [G]
was ganz andres zu tun
                        
So vergeht Jahr um Jahr 
   [C]            [G]
und ist mir längst klar
          [Em]               [D]           [G]
daß nichts bleibt, daß nichts bleibt wie es war.
