---
title: Kaspar
artist: Reinhard Mey
year: 1992

---

:::{.song-grid}
 E A D  G   B  E 
:::

   [Am]                  [D]
Sie sagten, er kaeme von Nuernberg her,
       [Am]
und er spraeche kein Wort.
        [Am]                 [D]   
Auf dem Marktplatz standen sie um ihn her
      [Am]
und begafften ihn dort.
   [C]                            [Am]
Die einen raunten: Er ist ein Tier!",  
          [Am] 
die andern fragten: Was will der hier?",
[D]                       [G]
und dass er sich doch zum Teufel scher'.
    [C]             E7      [Am]
So jagt ihn doch fort, so jagt ihn doch fort!"

Sein Haar in Straehnen und wirre,
sein Gang war gebeugt.
Seht, dieser arme Irre
ward vom Teufel gezeugt.
"Der Pfarrer reichte ihm einen Krug
voll Milch, er sog in einem Zug.
Der trinkt nicht vom Geschirre,
den hat die Woelfin gesaugt,
den hat die Woelfin gesaugt!"

Mein Vater, der in uns'rem Orte
Schulmeister war,
trat zu ihm hin, trotz boeser Worte
rings aus der Schar.
Er sprach zu ihm ganz ruhig, und
der Stumme oeffnete den Mund
und stammelte die Worte:
Heisse Kaspar, heisse Kaspar".

Mein Vater brachte ihn mit nach Haus:
Heisse Kaspar".
Meine Mutter wusch seine Kleider aus
und schnitt ihm das Haar.
Sprechen lehrte mein Vater ihn,
lesen und schreiben, und es schien,
was man ihn lehrte, sog er in sich auf -
wie gierig er war, wie gierig er war!

Zur Schule gehoerte derzeit
noch das Uttinger Feld,
Kaspar und ich, wir pflegten zu zweit,
bald war alles bestellt;
wie hegten und pflegten jeden Keim,
brachten im Herbst die Ernte ein,
von den Leuten vermaledeit,
von ihren Hunden verbellt,
von ihren Hunden verbellt.

Ein Wintertag, der Schnee lag frisch,
es war Januar.
Meine Mutter rief uns: Kommt zu Tisch,
das Essen ist gar!"
Mein Vater sagte: ...Appetit",
ich wartete auf Kaspars Schritt.
Mein Vater fragte mrrisch:
Wo bleibt Kaspar, wo bleibt Kaspar?"

Wir suchten, und wir fanden ihn
auf dem Pfad bei dem Feld.
Der Neuschnee wehte ueber ihn,
sein Gesicht war entstellt,
die Augen angstvoll aufgerissen,
sein Hemd war blutig und zerschlissen.
Erstochen hatten sie ihn,
dort am Uttinger Feld, dort am Uttinger Feld!

Der Polizeirat aus der Stadt
fuellte ein Formular.
Gott nehm' ihn hin in seiner Gnad"',
sagte der Herr Vikar.
Das Uttinger Feld liegt lang schon brach,
nur manchmal bell'n mir noch die Hunde nach,
dann streu' ich ein paar Blumen auf den Pfad
fuer Kaspar, fuer Kaspar. 

