---
title: Sie Hört Musik nur wenn sie Laut ist
artist: Herberg Grönemeyer

---

[Gm]                                 [F#]
Sie sitzt den ganzen Tag auf ihrer Fensterbank
[F]                     D#  [Bb]
lässt ihre Beine baumeln zur Musik.
[Gm]                                 [F#]
Der Lärm aus ihrem Zimmer macht alle Nachbarn krank,
[F]                          D#  [Bb]
sie ist beseelt, lächelt vergnügt.

[Dm]                    [Eb]                   [Bb]
Sie weiß nicht, dass der Schnee lautlos auf die Erde fällt,
[Dm]             [Eb]             [Bb] [F]
merkt nichts vom Klopfen an der Wand.


:::{.chorus}

       [Eb]                [Bb]
Sie mag Musik nur, wenn sie laut ist,
       [Eb]           [Bb]
das ist alles was sie hört,
       [Gm]                [Bb]
sie mag Musik nur, wenn sie laut ist,
    [C]                   [F]
wenn sie ihr in den Magen fährt.
       [Gm]                [Bb]
Sie mag Musik nur, wenn sie laut ist,
        [Eb]                  [Bb]
wenn der Boden unter den Füßen bebt,
        [Gm]                [F]        [G]
dann vergisst sie, dass sie taub ist.

:::


Gm                            [F#]
Der Mann ihrer Träume muss ein Bassmann sein
      [F]                      D#  [Bb]
das Kitzeln im Bauch macht sie verrückt,
 [Gm]                            [F#]
ihr Mund scheint vor lauter Glück still zu schrei'n
 [F]                     D#  [Bb]
ihr Blick ist der Welt entrückt

   [Dm]                     [Eb]                  [Bb]
ihre Hände wissen nicht, mit wem sie reden sollen
   [Dm]              [Eb]             [Bb] [F]
es ist niemand da, der mit ihr spricht.


*play chorus*
