---
title: Es ist für uns eine Zeit angekommen
artist: Rolf Zuckofski
---

D
Es ist für uns eine Zeit angekommen
                    A7      D
Die bringt uns eine große Freud
Es ist für uns eine Zeit angekommen
                    A7      D
Die bringt uns eine große Freud
        G      A7     D
Übers schneebedeckte Feld
        A7    D      A7
Wandern wir, wandern wir
 D                A7    D
Durch die weite, weiße Welt

             D
Es schlafen Bächlein und See unterm Eise
                           A7     D
Es traumt der Wald einen tiefen Traum
D
Es schlafen Bächlein und See unterm Eise
                           A7     D
Es traumt der Wald einen tiefen Traum
             G          A7    D
Durch den Schnee, der leise fällt
        A7    D      A7
Wandern wir, wandern wir
 D                A7    D   Dsus2
Durch die weite, weiße Welt

           D
Vom hohen Himmel ein leuchtendes Schweigen
                       A7    D
Erfüllt die Herzen mit Seligkeit
           D
Vom hohen Himmel ein leuchtendes Schweigen
                       A7    D
Erfüllt die Herzen mit Seligkeit
        G      A7       D
Unterm sternbeglänzten Zelt
        A7    D      A7
Wandern wir, wandern wir
 D    Em D/F# G  D/A A7 D
Durch die weite, weiße Welt