---
title: In der Weihnachtsbäckerei
artist: Rolf Zuckowski

---

       C         G    Am
In der Weihnachtsbäckerei 
         F      C    G
gibt es manche Leckerei.    
         Dm        G
Zwischen Mehl und Milch  
          Dm       G
macht so mancher Knilch    
      C     G     Am
eine riesengroße Kleckerei. 
        C        G    Am
In der Weihnachtsbäckerei  
        C        G    C
in der Weihnachtsbäckerei. 

C
Wo ist das Rezept geblieben
Dm
von den Plätzchen, die wir lieben?
G                        C
Wer hat das Rezept verschleppt?

C
Na, dann müssen wir es packen,
Dm
einfach frei nach Schnauze backen.                      
G                       C
Schmeißt den Ofen an und ran.

C
Brauchen wir nicht Schokolade,
Dm
Honig, Nüsse und Sukkade                                
G
und ein bißchen Zimt?
C
Das stimmt!

C
Butter, Mehl und Milch verrühren,
Dm
zwischendurch einmal probieren                  
G                            C
und dann kommt das Ei: Vorbei!

C
Bitte mal zur Seite treten,
Dm
denn wir brauchen Platz zum Kneten.                     
G
Sind die Finger rein?
C
Du Schwein!

C
Sind die Plätzchen, die wir stechen,
Dm
erst mal auf den Ofenblechen,                           
G
warten wir gespannt:
C
Verbrannt! 

       C         G    Am
In der Weihnachtsbäckerei 
         F      C    G
gibt es manche Leckerei.    
         Dm        G
Zwischen Mehl und Milch  
          Dm       G
macht so mancher Knilch    
      C     G     Am
eine riesengroße Kleckerei. 
        C        G    Am
In der Weihnachtsbäckerei  
        C        G    C
in der Weihnachtsbäckerei. 
