---
title: Marys Bornchild
capo: '0'
time: 6/6

---
<!--Verse-->
:::{.song-grid} 

G·····|C··Am·|D····|G·····|
G·····|C··Am·|D····|G·····|
:::

Long time ago in Bethlehem, 
so the Holy Bible says,  
Mary's boychild, Jesus Christ, 
was born on Christmas Day. 

<!--Chorus-->
:::{.song-grid} 
G··C··|D··G···|Em·Am·|D····|
G·····|C··Am··|G··D··|G····|
:::

::: {.callout appearance="minimal"}
Hark now! Hear the Angels sing, 
a King was born today, 
and man will live forever more 
because of Christmas Day. 
:::  

While shepherds watch their flocks by night, 
they see a bright new shining star. 
They hear a choir sing a song,  
the music seemed to come from afar.  
  
*play chorus* 

Now Joseph and his wife, Mary, 
came to Bethlehem that night. 
They found no place to bear the child,  
not a single room was in sight.      
  
*play chorus*

Trumpets sound and Angels sing...
listen to what they say, 
that man will live forever more 
because of Christmas Day. 

*play chorus*
*play chorus*
  
And then they found a little nook, 
in a stable all forlorn. 
And in a manger, cold and dark, 
Mary's little boy was born.

Long time ago in Bethlehem, 
so the Holy Bible says,  
Mary's boychild, Jesus Christ, 
was born on Christmas Day. 

  
*play chorus*

Trumpets sound and Angels sing...
listen to what they say, 
that man will live forever more 
because of Christmas Day.
