## Viva la Vida - Coldplay
\
<p class='song show-chords'>INTRO:<span class='chord'>C</span>-<span class='chord'>D</span>-<span class='chord'>G</span>-<span class='chord'>Em</span>   x2</p>
\
<p class='song show-chords'>I used to<span class='chord'>C</span> rule the<span class='chord'>D</span> world</p>
<p class='song show-chords'>Seas would<span class='chord'>G</span> rise when I gave the<span class='chord'>Em</span> word</p>
<p class='song show-chords'>Now in the morning I<span class='chord'>C</span> sleep a<span class='chord'>D</span>lone	</p>
<p class='song show-chords'>Sweep the<span class='chord'>G</span> streets I used to<span class='chord'>Em</span> own</p>
\
<p class='song show-chords'><span class='chord'>C</span><span class='chord'>D</span>-<span class='chord'>G</span>-<span class='chord'>Em</span>   x2</p>
\
I used to roll the dice \
Feel the fear in my enemy's eyes \
Listen as the crowd would sing \
"Now the old king is dead! Long live the king!" \
\
One minute I held the key \
Next the walls were closed on me \
And I discovered that my castles stand \
Upon pillars of salt and pillars of sand \
\
**Chorus:**\
<p class='song show-chords'>I<span class='chord'>C</span> hear Jerusalem<span class='chord'>D</span> bells are ringing</p>
<p class='song show-chords'><span class='chord'>G</span>Roman Cavalry<span class='chord'>Em</span> choirs are singing</p>
<p class='song show-chords'><span class='chord'>C</span>Be my mirror, my<span class='chord'>D</span> sword, and shield</p>
<p class='song show-chords'>My<span class='chord'>G</span> missionaries in a<span class='chord'>Em</span> foreign field</p>
<p class='song show-chords'><span class='chord'>C</span>For some reason I<span class='chord'>D</span> can't explain</p>
<p class='song show-chords'><span class='chord'>G</span>Once you go there was<span class='chord'>Em</span> never, never an<span class='chord'>C</span> honest<span class='chord'>D</span> word</p>
<p class='song show-chords'>That was<span class='chord'>Bm</span> when I ruled the<span class='chord'>Em</span> world</p>
\
<p class='song show-chords'><span class='chord'>C</span>{en<span class='chord'>D</span>d_of<span class='chord'>G</span>_cho<span class='chord'>Em</span>urs}</p>
\
It was the wicked and wild wind \
Blew down the doors to let me in \
Shattered windows and the sound of drums \
People couldn't believe what I'd become \
\
Revolutionaries wait \
For my head on a silver plate \
Just a puppet on a lonely string \
Oh who would ever want to be king? \
\
{chorus}\
\
<p class='song show-chords'><span class='chord'>C</span><span class='chord'>Em</span>x3</p>
<p class='song show-chords'><span class='chord'>D</span>2</p>
\
<p class='song show-chords'><span class='chord'>C</span>(Oh<span class='chord'>D</span>hhhh<span class='chord'>G</span> Ohh<span class='chord'>Em</span>h Ohhh)</p>
\
{chorus}\
\
<p class='song show-chords'><span class='chord'>C</span>Ooo<span class='chord'>D</span>ooh <span class='chord'>Bm</span>Ooooo<span class='chord'>Em</span>h Oooooh</p>
\
\
