## All the World is Green - Tom Waits
\
<p class='song show-chords'><span class='chord'>Bm</span>I fell into the<span class='chord'>Em</span> ocean<span class='chord'>A7</span>  and you became<span class='chord'>D</span> my wife</p>
<p class='song show-chords'><span class='chord'>G7</span> I risked it all against the sea to have a b<span class='chord'>Bm</span>etter life</p>
<p class='song show-chords'>Marie you <span class='chord'>Em</span>are the wild blue<span class='chord'>A7</span> sky, men do <span class='chord'>D</span>foolish things</p>
<p class='song show-chords'><span class='chord'>G7</span> You turn kings into beggars and beggars i<span class='chord'>Bm</span>nto kings</p>
\
**Chorus:**\
\
<p class='song show-chords'>Pr<span class='chord'>G</span>etend that you owe me<span class='chord'>D</span> nothing      </p>
<p class='song show-chords'>and<span class='chord'>A7</span> all the world is<span class='chord'>D</span> green</p>
<p class='song show-chords'><span class='chord'>G</span> We can bring back the<span class='chord'>D</span> old days again     </p>
<p class='song show-chords'>when<span class='chord'>A7</span> all the world is<span class='chord'>D</span> green</p>
\
\
\
The face forgives the mirror\
The worm forgives the plow\
The questions begs the answer\
Can you forgive me somehow?\
\
Maybe when our story's over\
We'll go where it's always spring\
The band is playing our song again\
<p class='song show-chords'>And all the world is green [Play Chorus]</p>
\
The moon is yellow silver\
On the things that summer brings\
It's a love you'd kill for\
And all the world is green\
\
He's balancing a diamond\
On a blade of grass\
The dew will settle on our graves\
When all the world is green\
\
{Comment: Play chorus, solo, repeat last verse}\
\
