## For the Windows in Paradise - Sufjan Stevens
\
<p class='song show-chords'><span class='chord'>Am</span>I have called you chil<span class='chord'>C</span>dren, I have cal<span class='chord'>G</span>led you son,</p>
<p class='song show-chords'><span class='chord'>Am</span>What is there to answe<span class='chord'>C</span>r when I'm t<span class='chord'>G</span>he only one?</p>
<p class='song show-chords'><span class='chord'>Am</span>Morning comes in par<span class='chord'>C</span>adise, morning<span class='chord'>G</span> comes in light,</p>
<p class='song show-chords'><span class='chord'>Am</span>Still I must obe<span class='chord'>C</span>y, s<span class='chord'>G</span>till I must invite.</p>
\
<p class='song show-chords'>If there's<span class='chord'>Am</span> anything to say, if th<span class='chord'>C</span>ere's<span class='chord'>G</span> anything to do,</p>
<p class='song show-chords'>If there's<span class='chord'>Am</span> any other way, <span class='chord'>C</span>I'll do a<span class='chord'>G</span>nything for you.</p>
\
I was dressed embarrassment. \
I was dressed in wine. \
If you had a part of me, will you take you're time? \
Even if I come back, even if I die \
Is there some idea to replace my life? \
\
Like a father to impress; \
Like a mother's mourning dress, \
If you ever make a mess, I'll do anything for you \
\
I have called you preacher; I have called you son. \
If you have a father or if you haven't one, \
I'll do anything for you (4x)\
\
I did everything for you (repeat.. about 8x)\
