## Wagon Wheel - Old Crow Medicin Show
\
<p class='song show-chords'><span class='chord'>G</span>Headed down south to the<span class='chord'>D</span> land of the pines</p>
<p class='song show-chords'>And I'm<span class='chord'>Em</span> thumbin' my way into<span class='chord'>C</span> North Caroline</p>
<p class='song show-chords'><span class='chord'>G</span>Starin' up the road</p>
<p class='song show-chords'>And pray to<span class='chord'>D</span> God I see<span class='chord'>C</span> headlights</p>
\
\
I made it down the coast in seventeen hours \
Pickin' me a bouquet of dogwood flowers \
And I'm a hopin' for Raleigh \
I can see my baby tonight\
\
**Chorus:**\
<p class='song show-chords'>So<span class='chord'>G</span> rock me mama like a<span class='chord'>D</span> wagon wheel</p>
<p class='song show-chords'><span class='chord'>Em</span>Rock me mama an<span class='chord'>C</span>yway you feel</p>
<p class='song show-chords'><span class='chord'>G</span>Hey<span class='chord'>D</span>, mama<span class='chord'>C</span> rock me</p>
<p class='song show-chords'><span class='chord'>G</span>Rock me mama like the<span class='chord'>D</span> wind and the rain</p>
<p class='song show-chords'><span class='chord'>Em</span>Rock me mama like a<span class='chord'>C</span> south-bound train</p>
<p class='song show-chords'><span class='chord'>G</span>Hey<span class='chord'>D</span>, mama<span class='chord'>C</span> rock me</p>
\
\
Intro\
\
Runnin' from the cold up in New England\
I was born to be a fiddler in an old-time stringband\
My baby plays the guitar\
I pick a banjo now\
\
Oh, the North country winters keep a gettin' me now\
Lost my money playin' poker so I had to up and leave\
But I ain't a turnin' back\
To livin' that old life no more\
\
{chorus}\
\
Walkin' to the south out of Roanoke\
I caught a trucker out of Philly\
Had a nice long toke\
But he's a headed west from the Cumberland Gap\
To Johnson City, Tennessee\
\
And I gotta get a move on before the sun\
I hear my baby callin' my name\
And I know that she's the only one\
And if I die in Raleigh\
At least I will die free\
\
{chorus}\
