## I will follow you into the Dark - Death Cab for Cutie
\
<p class='song show-chords'><span class='chord'>C</span>Love of mine</p>
<p class='song show-chords'>Someday you will<span class='chord'>Am</span> die</p>
<p class='song show-chords'>But I will be close b<span class='chord'>F</span>ehind</p>
<p class='song show-chords'>I will fol<span class='chord'>C</span>low, you into the d<span class='chord'>G</span>ark</p>
\
No blinding light\
Or tunnels to gates of white\
Just our hands clasped so tight\
Waiting for, the hint of a spark \
\
**Chorus:**\
<p class='song show-chords'>If<span class='chord'>Am</span> heaven and hell de<span class='chord'>C</span>cide,      </p>
<p class='song show-chords'>that they <span class='chord'>F</span>both are sat<span class='chord'>C</span>isfied</p>
<p class='song show-chords'><span class='chord'>Am</span>Illuminate the "<span class='chord'>C</span>no's", on their vacancy signs</p>
<p class='song show-chords'><span class='chord'>Am</span>If there's no one beside <span class='chord'>C</span>you,</p>
<p class='song show-chords'>when your <span class='chord'>E</span>soul em<span class='chord'>Am</span>barks</p>
<p class='song show-chords'>Then I will follow you into the d<span class='chord'>F</span>ark</p>
\
\
Catholic school\
As vicious as roman rule\
I got my knuckles bruised \
By a lady in black\
     \
And I held my tongue \
as she told me "son, fear is the heart of love." \
So I never went back\
\
{chorus}\
\
You and me, have seen everything to see\
From Bangkok to Calgary  \
And the soles of your shoes\
 \
Are all worn down, the time for sleep is now\
But it's nothing to cry about  \
Because we'll hold each other soon\
<p class='song show-chords'><span class='chord'>Am</span>in the blackest of rooms </p>
\
<p class='song show-chords'><span class='chord'>Am</span>If heaven and hell d<span class='chord'>C</span>ecide, </p>
<p class='song show-chords'>that they <span class='chord'>F</span>both are sati<span class='chord'>C</span>sfied</p>
<p class='song show-chords'><span class='chord'>Am</span>Illuminate the "<span class='chord'>C</span>no's", on their vacancy signs</p>
<p class='song show-chords'><span class='chord'>Am</span>If there's no one beside <span class='chord'>C</span>you, when your <span class='chord'>E</span>soul em<span class='chord'>Am</span>barks</p>
<p class='song show-chords'><span class='chord'>F</span>Then I will follow you into the<span class='chord'>C</span> dark</p>
\
```{class.source='chordgrid'}
E---------------------|\
B---1---1--------1----|\
G---2---2--------2----|\
D---0---0--------2----|\
A---3---2----0---0----|\
E---------------------|\
```{class.source='chordgrid'}
\
<p class='song show-chords'><span class='chord'>F</span>Then I will follow you into the<span class='chord'>C</span> dark</p>
\
\
