## Sweet Home Alabama - Lynyrd Skynyrd
\
```{}
e|-------------------------3-|\
B|-----3---------3---------3-|\
G|-------2----------0------0-|  x4\
D|-0-0---------------------0-|     \
A|----------3-3------------2-|\
E|---------------------3-3-3-|\
```
\
<p class='song show-chords'><span class='chord'>D</span>Big <span class='chord'>Cadd9</span>wheels keep on<span class='chord'>G</span> turning</p>
<p class='song show-chords'><span class='chord'>D</span>Carry me<span class='chord'>Cadd9</span> home to see my<span class='chord'>G</span> kin</p>
<p class='song show-chords'><span class='chord'>D</span>Singing<span class='chord'>Cadd9</span> songs about the<span class='chord'>G</span> south land</p>
<p class='song show-chords'><span class='chord'>D</span>I miss '<span class='chord'>Cadd9</span>ole' 'bamy once<span class='chord'>G</span> again and I think it's a sin</p>
\
<p class='song show-chords'><span class='chord'>D</span>Well I heard Mr.<span class='chord'>Cadd9</span> Young sing about<span class='chord'>G</span> her</p>
<p class='song show-chords'><span class='chord'>D</span>Well I heard old<span class='chord'>Cadd9</span> Neil put her<span class='chord'>G</span> down</p>
<p class='song show-chords'><span class='chord'>D</span>Well I hope Neil<span class='chord'>Cadd9</span> Young will<span class='chord'>G</span> remember</p>
<p class='song show-chords'><span class='chord'>D</span>       <span class='chord'>Cadd9</span>            <span class='chord'>G</span>               </p>
<p class='song show-chords'><span class='chord'>A</span>outhern man don’t need him around, anyhow</p>
\
<p class='song show-chords'><span class='chord'>Chorus</span></p>
\
**Chorus:**\
<p class='song show-chords'><span class='chord'>D</span>Sweet<span class='chord'>Cadd9</span> home Al<span class='chord'>G</span>abama,<span class='chord'>D</span> where the<span class='chord'>Cadd9</span> skies are so<span class='chord'>G</span> blue</p>
<p class='song show-chords'><span class='chord'>D</span>Sweet<span class='chord'>Cadd9</span> home Al<span class='chord'>G</span>abama,<span class='chord'>D</span> lord I’<span class='chord'>Cadd9</span>m coming home <span class='chord'>G</span>to you.</p>
\
\
<p class='song show-chords'><span class='chord'>F</span></p>
<p class='song show-chords'><span class='chord'>D</span>add9<span class='chord'>G</span></p>
<p class='song show-chords'><span class='chord'>D</span>add9<span class='chord'>G</span></p>
\
<p class='song show-chords'><span class='chord'>D</span>In Birmin<span class='chord'>Cadd9</span>gham they love the<span class='chord'>G</span> Gov'nor,<span class='chord'>F</span> boo<span class='chord'>C</span>-hoo<span class='chord'>D</span>-hoo</p>
<p class='song show-chords'><span class='chord'>D</span>Now we all<span class='chord'>Cadd9</span> did what we could<span class='chord'>G</span> do</p>
<p class='song show-chords'><span class='chord'>D</span>Now water<span class='chord'>Cadd9</span>gate doesn't<span class='chord'>G</span> bother me</p>
<p class='song show-chords'><span class='chord'>D</span>Does you <span class='chord'>Cadd9</span>conscience bother<span class='chord'>G</span> you, (now tell the truth!)</p>
\
{chorus}\
\
<p class='song show-chords'><span class='chord'>D</span>Now<span class='chord'>Cadd9</span> Muscle Shoals has got the<span class='chord'>G</span> Swappers</p>
<p class='song show-chords'><span class='chord'>D</span>And they've been<span class='chord'>Cadd9</span> known to pick a song or<span class='chord'>G</span> two (yes we do)</p>
<p class='song show-chords'><span class='chord'>D</span>Lord they<span class='chord'>Cadd9</span> get me off so<span class='chord'>G</span> much</p>
<p class='song show-chords'><span class='chord'>D</span>They pick me<span class='chord'>Cadd9</span> up when I'm feelin<span class='chord'>G</span>g blue, Now how about you?</p>
\
{chorus}\
\
<p class='song show-chords'><span class='chord'>D</span>Sweet<span class='chord'>Cadd9</span> home Al<span class='chord'>G</span>abama (Oh sweet home baby)</p>
<p class='song show-chords'><span class='chord'>D</span>Where the<span class='chord'>Cadd9</span> skies are so<span class='chord'>G</span> blue (And the governor's true)</p>
<p class='song show-chords'><span class='chord'>D</span>Sweet<span class='chord'>Cadd9</span> Home Al<span class='chord'>G</span>abama, (Lord, yeah)</p>
<p class='song show-chords'><span class='chord'>D</span>Lord, I'm<span class='chord'>Cadd9</span> coming home to<span class='chord'>G</span> you</p>
