## Calafornia Dreaming - the Mamas and the Papas
\
\
<p class='song show-chords'>All the leaves are br<span class='chord'>Am</span>own (all t<span class='chord'>G</span>he leaves a<span class='chord'>F</span>re brown)</p>
<p class='song show-chords'>And the<span class='chord'>G</span> sky is<span class='chord'>Am</span> gray  (and the sky is <span class='chord'>E</span>gray)</p>
<p class='song show-chords'>I've b<span class='chord'>F</span>een for a walk  <span class='chord'>C</span>(I've been <span class='chord'>E</span>for a<span class='chord'>Am</span> walk)</p>
<p class='song show-chords'>On a <span class='chord'>F</span>winter's <span class='chord'>Am</span>day  (on a winter's <span class='chord'>E</span>day)</p>
<p class='song show-chords'>I'd be <span class='chord'>E</span>safe and warm (I<span class='chord'>Am</span>'d be sa<span class='chord'>G</span>fe and wa<span class='chord'>F</span>rm)</p>
<p class='song show-chords'>If I<span class='chord'>G</span> was in<span class='chord'>Am</span> L.A.  (if I was in<span class='chord'>E</span> L.A.)</p>
\
**Chorus:**\
<p class='song show-chords'><span class='chord'>E</span>California dr<span class='chord'>Am</span>eamin  (C<span class='chord'>G</span>alifornia <span class='chord'>F</span>dreamin')</p>
<p class='song show-chords'>On <span class='chord'>G</span>such a <span class='chord'>Am</span>winter's <span class='chord'>E</span>day</p>
\
\
\
<p class='song show-chords'><span class='chord'>E</span>Stopped in to a<span class='chord'>Am</span> church</p>
<p class='song show-chords'>I<span class='chord'>G</span> passed along<span class='chord'>F</span> the way</p>
<p class='song show-chords'>Well I <span class='chord'>G</span>got down on my <span class='chord'>Am</span>knees (got down <span class='chord'>E</span>on my knees)</p>
<p class='song show-chords'><span class='chord'>F</span>And I pretend to<span class='chord'>Am</span> pray (I pretend to<span class='chord'>E</span> pray)</p>
<p class='song show-chords'><span class='chord'>E</span>You know the preacher<span class='chord'>Am</span> likes the<span class='chord'>G</span> cold (preacher lik<span class='chord'>F</span>es the cold)</p>
<p class='song show-chords'>He knows<span class='chord'>G</span> I'm gonna<span class='chord'>Am</span> stay (knows I'm gonna<span class='chord'>E</span> stay)</p>
\
{chorus}\
\
<p class='song show-chords'><span class='chord'>E</span>All the leaves ar<span class='chord'>Am</span>e brown (a<span class='chord'>G</span>ll the leav<span class='chord'>F</span>es are brown)</p>
<p class='song show-chords'>And the<span class='chord'>G</span> sky is<span class='chord'>Am</span> gray (and the sky is g<span class='chord'>E</span>ray)</p>
<p class='song show-chords'><span class='chord'>F</span>I've been for a<span class='chord'>C</span> walk (I've<span class='chord'>E</span> been<span class='chord'>Am</span> for a walk)</p>
<p class='song show-chords'>On a<span class='chord'>F</span> winter's<span class='chord'>Am</span> day  (on a winter's<span class='chord'>E</span> day)</p>
<p class='song show-chords'>If I di<span class='chord'>E</span>dn't tell her  (<span class='chord'>Am</span>if I did<span class='chord'>G</span>n't tell <span class='chord'>F</span>her)</p>
<p class='song show-chords'>I could<span class='chord'>G</span> leave<span class='chord'>Am</span> today (I could leave<span class='chord'>E</span> today)</p>
\
<p class='song show-chords'><span class='chord'>E</span>California dr<span class='chord'>Am</span>eamin (Ca<span class='chord'>G</span>lifornia d<span class='chord'>F</span>reamin')</p>
<p class='song show-chords'>On<span class='chord'>G</span> such a<span class='chord'>Am</span> winter's<span class='chord'>E</span> day (Califor<span class='chord'>G</span>nia dream<span class='chord'>F</span>in')</p>
<p class='song show-chords'>On<span class='chord'>G</span> such a<span class='chord'>Am</span> winter's<span class='chord'>E</span> day (Califor<span class='chord'>G</span>nia dream<span class='chord'>F</span>in')</p>
<p class='song show-chords'>On<span class='chord'>G</span> such a<span class='chord'>Am</span> winter's<span class='chord'>E</span> day<span class='chord'>Am</span></p>
\
