## Lemon Tree - Fools Garden
\
```
Em__|Bm__|Em__|Bm__|\
Am__|Bm__|Em__|Bm_E|\
```
\
<p class='song show-chords'><span class='chord'>Em</span>             <span class='chord'>Bm</span></p>
<p class='song show-chords'>I'm Sitting Here In<span class='chord'>A</span>Boring Room</p>
<p class='song show-chords'><span class='chord'>Em</span>It's Just Another Rainy Sunday<span class='chord'>Bm</span> Afternoon</p>
<p class='song show-chords'><span class='chord'>Em</span>I'm Wasting My Time I Got<span class='chord'>Bm</span> Nothing To Do</p>
<p class='song show-chords'><span class='chord'>Em</span>I'm Hanging Around I'm<span class='chord'>Bm</span> Waiting For You</p>
<p class='song show-chords'>But<span class='chord'>Am</span> Nothing Ever Happens<span class='chord'>Bm</span> - And I<span class='chord'>Em</span> Wond<span class='chord'>Bm</span>er<span class='chord'>Em</span></p>
\
I'm Driving Around In My Car\
I'm Driving Too Fast I'm Driving Too Far\
I'd Like To Change My Point Of View\
I Feel So Lonely I'm Waiting For You\
But Nothing Ever Happens - And I Wonder\
\
Chorus\
<p class='song show-chords'><span class='chord'>G</span>I Wonder How I<span class='chord'>D</span> Wonder Why</p>
<p class='song show-chords'><span class='chord'>Em</span>Yesterday You Told Me 'bout The<span class='chord'>Bm</span> Blue Blue Sky</p>
<p class='song show-chords'><span class='chord'>C</span>               <span class='chord'>D</span>                  <span class='chord'>G</span>       <span class='chord'>D</span></p>
<p class='song show-chords'>And All That I Can See Is Just<span class='chord'>A</span>Yellow Lemon-tree</p>
<p class='song show-chords'><span class='chord'>G</span>I'm Turning My Head<span class='chord'>D</span> Up And Down</p>
<p class='song show-chords'><span class='chord'>Em</span> I'm Turning Turning Turning Turning<span class='chord'>Bm</span> Turning Around</p>
<p class='song show-chords'><span class='chord'>C</span>And All That I Can<span class='chord'>A</span> See Is Just another <span class='chord'>D</span>Lemon-tree</p>
\
\
{start_of_bridge}\
 Em Bm Em Bm Am Bm Em \
 dadada....\
{end_of_bridge}\
\
\
I'm Sitting Here I Miss The Power\
I'd Like To Go Out Taking a Shower\
But There's a Heavy Cloud Inside My Head\
I Feel So Tired Put Myself Into Bed\
Where Nothing Ever Happens - And I Wonder\
\
<p class='song show-chords'><span class='chord'>B</span>Isolation - <span class='chord'>Em</span>Is Not Good For Me</p>
<p class='song show-chords'><span class='chord'>D</span>Isolation -<span class='chord'>G</span> I Don't Want To <span class='chord'>B</span>Sit On a Lemon-tree</p>
\
I'm Steppin' Around In a Desert Of Joy\
Baby Anyhow I'll Get Another Toy\
And Everything Will Happen - And You'll Wonder\
\
Chorus 2x\
\
<p class='song show-chords'><span class='chord'>C</span>And All That I Can<span class='chord'>D</span> See</p>
<p class='song show-chords'><span class='chord'>C</span>And All That I Can<span class='chord'>D</span> See</p>
<p class='song show-chords'><span class='chord'>C</span>And All That I Can<span class='chord'>D</span> See</p>
<p class='song show-chords'>Is Just a Yellow<span class='chord'>G</span> Lemon-tree.</p>
\
\
