## Sound of Silence - Simon and Garfunkel
\
<p class='song show-chords'><span class='chord'>Am</span>Hello darkness, my old f<span class='chord'>G</span>riend,</p>
<p class='song show-chords'>I've come to talk with you<span class='chord'>Am</span> again,</p>
<p class='song show-chords'>Because a vision <span class='chord'>F</span>softly<span class='chord'>C</span> creeping,</p>
<p class='song show-chords'>Left its<span class='chord'>Am</span> seeds while I <span class='chord'>F</span>was sl<span class='chord'>C</span>eeping,</p>
<p class='song show-chords'>And the <span class='chord'>F</span>vision that was planted in my br<span class='chord'>C</span>ain</p>
<p class='song show-chords'>Still <span class='chord'>Am</span>remains</p>
<p class='song show-chords'>Within the s<span class='chord'>G</span>ound of <span class='chord'>Am</span>silence.</p>
\
<p class='song show-chords'><span class='chord'>Am</span>In restless dreams I walked <span class='chord'>G</span>alone</p>
<p class='song show-chords'>Narrow streets of cobbl<span class='chord'>Am</span>estone,</p>
<p class='song show-chords'><span class='chord'>Am</span>'Neath the halo of <span class='chord'>F</span>a street <span class='chord'>C</span>lamp,</p>
<p class='song show-chords'>I turned my c<span class='chord'>Am</span>ollar to the <span class='chord'>F</span>cold and <span class='chord'>C</span>damp</p>
<p class='song show-chords'>When my<span class='chord'>F</span> eyes were stabbed by the flash of a neon <span class='chord'>C</span>light</p>
<p class='song show-chords'>That split the<span class='chord'>Am</span> night</p>
<p class='song show-chords'>And touched the<span class='chord'>G</span> sound of<span class='chord'>Am</span> silence.</p>
\
<p class='song show-chords'><span class='chord'>Am</span>And in the naked light I s<span class='chord'>G</span>aw</p>
<p class='song show-chords'>Ten thousand people, maybe<span class='chord'>Am</span> more.</p>
<p class='song show-chords'><span class='chord'>Am</span>People talking wi<span class='chord'>F</span>thout sp<span class='chord'>C</span>eaking,</p>
<p class='song show-chords'><span class='chord'>Am</span>People hearing withou<span class='chord'>F</span>t listen<span class='chord'>C</span>ing,</p>
<p class='song show-chords'>People writing s<span class='chord'>F</span>ongs that voices never s<span class='chord'>C</span>hare</p>
<p class='song show-chords'>And no one<span class='chord'>Am</span> dare</p>
<p class='song show-chords'>Disturb the <span class='chord'>G</span>sound of <span class='chord'>Am</span>silence.</p>
\
<p class='song show-chords'><span class='chord'>Am</span>Fools said I, you do not k<span class='chord'>G</span>now</p>
<p class='song show-chords'>Silence like a cancer<span class='chord'>Am</span> grows.</p>
<p class='song show-chords'><span class='chord'>Am</span>Hear my words that I m<span class='chord'>F</span>ight teach <span class='chord'>C</span>you,</p>
<p class='song show-chords'><span class='chord'>Am</span>Take my arms that I m<span class='chord'>F</span>ight reach y<span class='chord'>C</span>ou.</p>
<p class='song show-chords'>But my w<span class='chord'>F</span>ords like silent raindrops <span class='chord'>C</span>fell,</p>
<p class='song show-chords'>And e<span class='chord'>Am</span>choed</p>
<p class='song show-chords'>In the<span class='chord'>G</span> wells of<span class='chord'>Am</span> silence</p>
\
<p class='song show-chords'><span class='chord'>Am</span>And the people bowed and <span class='chord'>G</span>prayed</p>
<p class='song show-chords'>To the neon God they<span class='chord'>Am</span> made.</p>
<p class='song show-chords'><span class='chord'>Am</span> And the sign flashed out <span class='chord'>F</span>its war<span class='chord'>C</span>ning,</p>
<p class='song show-chords'><span class='chord'>Am</span>In the words that it w<span class='chord'>F</span>as for<span class='chord'>C</span>ming.</p>
<p class='song show-chords'>And the <span class='chord'>Am</span>sign said, the w<span class='chord'>F</span>ords of the prophets</p>
<p class='song show-chords'>Are wri<span class='chord'>F</span>tten on the subway wa<span class='chord'>C</span>lls</p>
<p class='song show-chords'>And tenement h<span class='chord'>Am</span>alls.</p>
<p class='song show-chords'>And whispered in the <span class='chord'>G</span>sounds of <span class='chord'>Am</span>silence.</p>
