## Moring has broken - Cat Stevens
\
<p class='song show-chords'>Morning has<span class='chord'>C</span> brok-en,<span class='chord'>G</span> like the first<span class='chord'>F</span> morn<span class='chord'>C</span>-ing</p>
<p class='song show-chords'><span class='chord'>C</span>Blackbird has<span class='chord'>Em</span> spok<span class='chord'>Am</span>-en,<span class='chord'>D7</span> like the first<span class='chord'>G</span> bir<span class='chord'>G</span>d</p>
<p class='song show-chords'><span class='chord'>C</span>Praise for the<span class='chord'>F</span> sing<span class='chord'>F</span>-ing,<span class='chord'>C</span> praise for the<span class='chord'>Am</span> morn<span class='chord'>D</span>-ing</p>
<p class='song show-chords'><span class='chord'>G</span>Praise for them<span class='chord'>C</span> spring<span class='chord'>F</span>-ing<span class='chord'>G</span> fresh from the<span class='chord'>C</span> world</p>
\
<p class='song show-chords'>Sweet the rain's<span class='chord'>C</span> new fall,<span class='chord'>G</span> sunlit from<span class='chord'>F</span> heav<span class='chord'>C</span>-en</p>
<p class='song show-chords'><span class='chord'>C</span>Like the first<span class='chord'>Em</span> dew<span class='chord'>Am</span> fall,<span class='chord'>D7</span> on the first<span class='chord'>G</span> gras<span class='chord'>G</span>s</p>
<p class='song show-chords'><span class='chord'>C</span>Praise for the<span class='chord'>F</span> sweet<span class='chord'>F</span>-ness<span class='chord'>C</span> of the wet<span class='chord'>Am</span> gard<span class='chord'>D</span>-en</p>
<p class='song show-chords'><span class='chord'>G</span>Sprung in<span class='chord'>C</span> complete<span class='chord'>F</span>-ness<span class='chord'>G</span> where his feet<span class='chord'>C</span> pass</p>
\
<p class='song show-chords'>Mine is the<span class='chord'>D</span> sun<span class='chord'>Em</span>light,<span class='chord'>A</span> mine is the<span class='chord'>G</span> morn<span class='chord'>D</span>-ing</p>
<p class='song show-chords'><span class='chord'>D</span>Born of the one light,<span class='chord'>E</span> Eden saw<span class='chord'>A</span> pla<span class='chord'>A</span>y</p>
<p class='song show-chords'><span class='chord'>D</span>Praise with<span class='chord'>G</span> ela<span class='chord'>G</span>-tion,<span class='chord'>D</span> praise every<span class='chord'>Bm</span> morn<span class='chord'>E</span>-ing</p>
<p class='song show-chords'><span class='chord'>A</span>God's<span class='chord'>D</span> recrea<span class='chord'>G</span>-tion<span class='chord'>A</span> of the new<span class='chord'>D</span> day</p>
\
<p class='song show-chords'>Morning has<span class='chord'>C</span> brok-en,<span class='chord'>G</span> like the first<span class='chord'>F</span> morn<span class='chord'>C</span>-ing</p>
<p class='song show-chords'><span class='chord'>C</span>Blackbird has<span class='chord'>Em</span> spok<span class='chord'>Am</span>-en,<span class='chord'>D7</span> like the first<span class='chord'>G</span> bir<span class='chord'>G</span>d</p>
<p class='song show-chords'><span class='chord'>C</span>Praise for the<span class='chord'>F</span> sing<span class='chord'>F</span>-ing,<span class='chord'>C</span> praise for the<span class='chord'>Am</span> morn<span class='chord'>D</span>-ing</p>
<p class='song show-chords'><span class='chord'>G</span>Praise for them<span class='chord'>C</span> spring<span class='chord'>F</span>-ing<span class='chord'>G</span> fresh from the<span class='chord'>C</span> world</p>
