## Blowing in the Wind - Bob Dylan
\
<p class='song show-chords'><span class='chord'>C</span>How many r<span class='chord'>F</span>oads must a<span class='chord'>C</span> man walk<span class='chord'>Am</span> down, </p>
<p class='song show-chords'>be<span class='chord'>C</span>fore you ca<span class='chord'>F</span>ll hi<span class='chord'>G</span>m a <span class='chord'>G7</span>man?</p>
<p class='song show-chords'><span class='chord'>C</span>How many<span class='chord'>F</span> seas must a <span class='chord'>C</span>white dove<span class='chord'>Am</span> sail, </p>
<p class='song show-chords'>be<span class='chord'>C</span>fore she sl<span class='chord'>F</span>eeps in the<span class='chord'>G</span> san<span class='chord'>G7</span>d?</p>
<p class='song show-chords'><span class='chord'>C</span>How many<span class='chord'>F</span> times must the ca<span class='chord'>C</span>nnonb<span class='chord'>Am</span>alls fly, </p>
<p class='song show-chords'>be<span class='chord'>C</span>fore they're f<span class='chord'>F</span>orever <span class='chord'>G</span>banned?</p>
<p class='song show-chords'>The an<span class='chord'>F</span>swer my fr<span class='chord'>G</span>iend, is blowing in the wind.</p>
<p class='song show-chords'>The an<span class='chord'>F</span>swer is bl<span class='chord'>G</span>owing in the<span class='chord'>C</span> wind.</p>
\
How many years must a mountain exist, \
before it is washed to the sea?\
How many years can some people exist, \
before they're allowed to be free? \
How many times can a man turn his head, \
and pretend that he just doesn't see?\
The answer my friend, is blowing in the wind.\
The answer is blowing in the wind.\
\
How many times must a man look up, \
before he can see the sky?\
How many ears must one man have, \
before he can hear people cry?\
How many deaths will it take 'till he knows, \
that too many people have Died?\
The answer my friend, is blowing in the wind.\
The answer is blowing in the wind.\
\
\
