## Hurst - Johnny Cash
\
<p class='song show-chords'><span class='chord'>Am</span> <span class='chord'>C</span><span class='chord'>D</span><span class='chord'>Am</span>  <span class='chord'>C</span><span class='chord'>D</span></p>
\
\
<p class='song show-chords'><span class='chord'>Am</span>   I<span class='chord'>C</span> hurt my<span class='chord'>D</span>self t<span class='chord'>Am</span>oday   to<span class='chord'>C</span> see if<span class='chord'>D</span> I still<span class='chord'>Am</span> feel</p>
<p class='song show-chords'>I<span class='chord'>C</span> focu<span class='chord'>D</span>s on the <span class='chord'>Am</span>pain   the<span class='chord'>C</span> only t<span class='chord'>D</span>hing that's<span class='chord'>Am</span> real</p>
<p class='song show-chords'>The<span class='chord'>C</span> needle<span class='chord'>D</span> tears a<span class='chord'>Am</span> hole   the<span class='chord'>C</span> old fa<span class='chord'>D</span>miliar s<span class='chord'>Am</span>ting</p>
<p class='song show-chords'>Try to<span class='chord'>C</span> kill i<span class='chord'>D</span>t all a<span class='chord'>Am</span>way   but I r<span class='chord'>C</span>emember<span class='chord'>D</span> everyt<span class='chord'>G</span>hing</p>
\
\
<p class='song show-chords'><span class='chord'>Am</span>What have I bec<span class='chord'>F</span>ome?  <span class='chord'>C</span>   My sweetest f<span class='chord'>G</span>riend</p>
<p class='song show-chords'><span class='chord'>Am</span>Everyone I <span class='chord'>F</span>know  goes awa<span class='chord'>C</span>y in the <span class='chord'>G</span>end</p>
<p class='song show-chords'>And<span class='chord'>Am</span> you could have it <span class='chord'>F</span>all  <span class='chord'>G</span> My empire of di<span class='chord'>G</span>rt</p>
<p class='song show-chords'><span class='chord'>Am</span>I will let you <span class='chord'>F</span>down   <span class='chord'>G</span> I will make you <span class='chord'>Am</span>hurt</p>
\
\
<p class='song show-chords'><span class='chord'>Am</span>  <span class='chord'>C</span><span class='chord'>D</span><span class='chord'>Am</span>  <span class='chord'>C</span><span class='chord'>D</span></p>
\
\
<p class='song show-chords'><span class='chord'>Am</span>   I<span class='chord'>C</span> wear this<span class='chord'>D</span> crown of<span class='chord'>Am</span> thorns   <span class='chord'>C</span>upon my<span class='chord'>D</span> liar's <span class='chord'>Am</span>chair</p>
<p class='song show-chords'><span class='chord'>C</span>Full of<span class='chord'>D</span> broken t<span class='chord'>Am</span>houghts  <span class='chord'>C</span> I can<span class='chord'>D</span>not r<span class='chord'>Am</span>epair</p>
<p class='song show-chords'>B<span class='chord'>C</span>eneath the <span class='chord'>D</span>stains of<span class='chord'>Am</span> time   the<span class='chord'>C</span> feeling<span class='chord'>D</span>s disapp<span class='chord'>Am</span>ear</p>
<p class='song show-chords'><span class='chord'>C</span>You are s<span class='chord'>D</span>omeone <span class='chord'>Am</span>else  <span class='chord'>C</span> I am <span class='chord'>D</span>still right <span class='chord'>G</span>here</p>
\
\
<p class='song show-chords'><span class='chord'>Am</span>What have I bec<span class='chord'>F</span>ome?  <span class='chord'>C</span>   My sweetest f<span class='chord'>G</span>riend</p>
<p class='song show-chords'><span class='chord'>Am</span>Everyone I <span class='chord'>F</span>know  goes awa<span class='chord'>C</span>y in the <span class='chord'>G</span>end</p>
<p class='song show-chords'>And<span class='chord'>Am</span> you could have it <span class='chord'>F</span>all  <span class='chord'>G</span> My empire of<span class='chord'>G</span> dirt</p>
<p class='song show-chords'><span class='chord'>Am</span>I will let you <span class='chord'>F</span>down  <span class='chord'>G</span> I will make you<span class='chord'>G</span> hurt</p>
<p class='song show-chords'>If<span class='chord'>Am</span> I could start ag<span class='chord'>F</span>ain  a<span class='chord'>G</span> million miles <span class='chord'>G</span>away</p>
<p class='song show-chords'><span class='chord'>Am</span>I would keep my<span class='chord'>F</span>self <span class='chord'>G</span> I would find a way</p>
