## Dr Alpeflug - Mani Matter
\
```
Am____|___E__|______|___Am_|\
______|___Dm_|___E__|Am____|\
```
\
<p class='song show-chords'><span class='chord'>Am</span>S'sy zwee Fründen im ne Sportflugzüg</p>
<p class='song show-chords'>En Alpeflug ga <span class='chord'>E</span>mache</p>
\
Flügen ufe zu de Gipflen und\
<p class='song show-chords'>Z'dürab de Gletsche<span class='chord'>Am</span>r nache</p>
\
Hinde sitzt dr Passagier\
<p class='song show-chords'>Dä wo stüüret, dä s<span class='chord'>Dm</span>itzt vor</p>
<p class='song show-chords'>Und es ratteret und <span class='chord'>Am</span>brummet</p>
<p class='song show-chords'>Um sen<span class='chord'>E</span> ume dr<span class='chord'>Am</span> Motor</p>
\
Da rüeft dä, wo hinde sitzt:\
Lue, ds Bänzin geit us, muesch lande!\
Wie? Was seisch? rüeft dr Pilot\
Los, i ha di nid verstande\
Wie? Was hesch gseit? rüeft dä hinde\
Warum landisch nid sofort?\
Red doch lüter, rüeft dä vorne\
Bi däm Krach ghör i kes wort\
\
I versta's nid, rüeft dä hinde\
Warum machsch's nid? Bisch drgäge?\
I versta's nid, rüeft dä vorne\
Muesch mer's würklech lüter säge!\
Wie? Was seisch? rüeft dise, lue\
Dr Tank isch läär, du flügsch nümm wyt!\
Los, bi däm Mordstonnerslärme\
Rüeft dä vorne, ghör i nüt\
\
Aber los doch, rüeft dä hinde\
Gottfridstutz mir hei nid d'Weli\
Tue nid ufgregt, rüeft dä vorne\
Red doch lüter, gottverteli!\
Los, rüeft dise, we mir jitz nid lande\
Gheie mir i ds Tal!\
Ghöre gäng no nüt, rüeft äine\
Los begryf doch das emal!\
\
So het im Motorelärme\
Dr Pilot halt nid verstande\
Dass ihm jitz ds Bänzin chönnt usga\
Und dass är sofort sött lande\
Da uf ds mal wird's plötzlech still\
Nämlech wil ds Bänzin usgeit\
Und jitz wo me's hätt verstande\
Hei si beidi nüt meh gseit \
\
\
