## Testament - Sarah Lesch
\
\
<p class='song show-chords'>Auch<span class='chord'>Em</span> du warst mal ein Kind und auch ich war mal klein</p>
<p class='song show-chords'>Und auch<span class='chord'>D</span> uns ham sie was er<span class='chord'>Em</span>zählt</p>
<p class='song show-chords'>Und dann<span class='chord'>Em</span> macht man das alles und versucht so zu sein</p>
<p class='song show-chords'>Und dann <span class='chord'>D</span>merkt man das einem was <span class='chord'>Em</span>fehlt</p>
<p class='song show-chords'>Und dann ver<span class='chord'>Em</span>lernt man, sich richtig zu spüren</p>
<p class='song show-chords'>Und man f<span class='chord'>D</span>lüchtet sich in Kunst oder K<span class='chord'>Em</span>onsum</p>
<p class='song show-chords'>Und <span class='chord'>Em</span>während ihr fleißig Pläne macht,</p>
<p class='song show-chords'><span class='chord'>D</span>Lachen die Götter sich<span class='chord'>Em</span> krumm</p>
\
<p class='song show-chords'>Lasst eure <span class='chord'>H7</span>Kinder mal was dazu <span class='chord'>Em</span>sagen</p>
<p class='song show-chords'><span class='chord'>H7</span>Hört ihnen richti<span class='chord'>Em</span>g zu.</p>
<p class='song show-chords'>Die <span class='chord'>H7</span>spürn sich noch, die ham<span class='chord'>Em</span> Feeling für die Welt</p>
<p class='song show-chords'>Die sind <span class='chord'>Am</span>klüger als ich un<span class='chord'>H7</span>d du</p>
\
<p class='song show-chords'>Und <span class='chord'>C</span>denkt dran bevor ihr <span class='chord'>G</span>antwortet:</p>
<p class='song show-chords'>Ihr seid<span class='chord'>H7</span> auch nur verletzte <span class='chord'>Em</span>Kinder.</p>
<p class='song show-chords'>   <span class='chord'>C</span>                     <span class='chord'>G</span></p>
<p class='song show-chords'><span class='chord'>Am</span>nde gibt’s wieder ganz neue Symptome,</p>
<p class='song show-chords'>und<span class='chord'>H7</span> ihr wart die Er<span class='chord'>Em</span>finder</p>
<p class='song show-chords'>Und dann <span class='chord'>C</span>sagt ihnen wieder, wie es <span class='chord'>G</span>richtig geht</p>
<p class='song show-chords'>„Werd<span class='chord'>H7</span> erwachsen“ <span class='chord'>Em</span>und „bist du naiv“</p>
<p class='song show-chords'>Predigt <span class='chord'>C</span>Formeln, lasst alles in <span class='chord'>G</span>Hefte schreiben,</p>
<p class='song show-chords'>Die <span class='chord'>Em</span>Götter lachen sich s<span class='chord'>D</span>chief</p>
<p class='song show-chords'><span class='chord'>Em</span>Achtet auf Schönschrift und Lehrpläne</p>
<p class='song show-chords'>Un<span class='chord'>D</span>d dass sie die Bleistifte <span class='chord'>Em</span>spitzen</p>
<p class='song show-chords'><span class='chord'>Em</span>Zeigt ihnen Bilder von Eichenblättern </p>
<p class='song show-chords'>Während sie <span class='chord'>D</span>drinnen an Tischen<span class='chord'>Em</span> sitzen</p>
<p class='song show-chords'>Und dann<span class='chord'>Em</span> ackern und büffeln und wieder auskotzen</p>
<p class='song show-chords'>Und am <span class='chord'>D</span>Nachmittag RTL 2</p>
<p class='song show-chords'>  <span class='chord'>Em</span></p>
<p class='song show-chords'><span class='chord'>Am</span>ochenende geht’s was Schönes kaufen, </p>
<p class='song show-chords'><span class='chord'>D</span>fertig ist der Einheitsbre<span class='chord'>Em</span>i</p>
<p class='song show-chords'>Und <span class='chord'>Em</span>jeder der sich nicht anpasst</p>
<p class='song show-chords'>Wird<span class='chord'>D</span> zum Problemkind erkl<span class='chord'>Em</span>ärt</p>
<p class='song show-chords'>Und<span class='chord'>Em</span> jede, die zu lebhaft ist</p>
<p class='song show-chords'>Kriegt ‘<span class='chord'>Am</span>ne Pille damit sie nicht<span class='chord'>H7</span> stört</p>
\
<p class='song show-chords'>Und d<span class='chord'>H7</span>amit betrügt ihr euch<span class='chord'>Em</span> selber denn</p>
<p class='song show-chords'><span class='chord'>H7</span>Kein Kind ist ein P<span class='chord'>Em</span>roblem</p>
<p class='song show-chords'>Und all die F<span class='chord'>H7</span>reigeister, all die S<span class='chord'>Em</span>chulschwänzer</p>
<p class='song show-chords'>Nur Sym<span class='chord'>Am</span>ptomträger im S<span class='chord'>H7</span>ystem</p>
\
\
<p class='song show-chords'>Doch bedenkt w<span class='chord'>C</span>enn ihr so hart<span class='chord'>G</span> urteilt:</p>
<p class='song show-chords'>Ihr seid<span class='chord'>H7</span> auch nur gefangene <span class='chord'>Em</span>Geister</p>
<p class='song show-chords'>Der<span class='chord'>C</span> Unmut wird immer <span class='chord'>G</span>lauter </p>
<p class='song show-chords'>Und die <span class='chord'>H7</span>Lehrer schreien sich <span class='chord'>Em</span>heiser</p>
<p class='song show-chords'><span class='chord'>C</span>Empört euch, dass Hänschen nicht <span class='chord'>G</span>ist, was er sein soll,</p>
<p class='song show-chords'>Sondern<span class='chord'>H7</span> nur, wer er nunmal <span class='chord'>Em</span>ist</p>
<p class='song show-chords'>Die <span class='chord'>C</span>Götter pullern sich<span class='chord'>G</span> ein vor Lachen</p>
<p class='song show-chords'>Und<span class='chord'>Em</span> ihr denkt, dass ihr was <span class='chord'>D</span>wisst</p>
\
 \
<p class='song show-chords'><span class='chord'>Em</span>Und wenn Hänschen dann Hans ist Der eigene Kinder hat, </p>
<p class='song show-chords'><span class='chord'>D</span>denen er was erz<span class='chord'>Em</span>ählt </p>
<p class='song show-chords'>Dann<span class='chord'>Em</span> merkt Hans und Kunz, und ihr vielleicht auch,</p>
<p class='song show-chords'>Dass <span class='chord'>D</span>wieder irgendwas <span class='chord'>Em</span>fehlt </p>
<p class='song show-chords'>Ihr h<span class='chord'>Em</span>abt Wünsche und Träume und rennt damit ständig </p>
<p class='song show-chords'><span class='chord'>D</span>an imaginäre<span class='chord'>Em</span> Wände</p>
<p class='song show-chords'>Und jeder <span class='chord'>Em</span>Wunsch den ihr euch erfüllt </p>
<p class='song show-chords'>Der ist <span class='chord'>D</span>dann halt auch zu<span class='chord'>Em</span> Ende</p>
<p class='song show-chords'>Geht<span class='chord'>Em</span> ihr nur Malochen für erfundene Zahlen</p>
<p class='song show-chords'>Und w<span class='chord'>D</span>artet, bis die Burnouts <span class='chord'>Em</span>kommen</p>
<p class='song show-chords'>Sc<span class='chord'>Em</span>hmeißt euer Geld für Plastik raus</p>
<p class='song show-chords'>Um ein k<span class='chord'>D</span>leines Glück zu <span class='chord'>Em</span>bekommen</p>
<p class='song show-chords'>Das<span class='chord'>Em</span> Beste aus Cerealien und Milch</p>
<p class='song show-chords'>Noch ‘<span class='chord'>D</span>n Carport und noch ‘<span class='chord'>Em</span>n Kredit</p>
<p class='song show-chords'>|: Und <span class='chord'>Em</span>alle finden‘s scheiße        </p>
<p class='song show-chords'> aber <span class='chord'>D</span>alle machen sie<span class='chord'>Em</span> mit :|         </p>
\
<p class='song show-chords'>Ihr <span class='chord'>H7</span>klugscheißert und kauft<span class='chord'>Em</span> trotzdem</p>
<p class='song show-chords'>Und die <span class='chord'>H7</span>Werbung verkauft euch für<span class='chord'>Em</span> dumm</p>
<p class='song show-chords'>Und dann <span class='chord'>H7</span>sitzt ihr vor neuen <span class='chord'>Em</span>Flachbildfernsehern</p>
<p class='song show-chords'>Und <span class='chord'>H7</span>meckert auf den K<span class='chord'>Em</span>onsum</p>
<p class='song show-chords'>Wenn ihr d<span class='chord'>H7</span>as Welt nennt, bin ich g<span class='chord'>Em</span>ern weltfremd</p>
<p class='song show-chords'>Die <span class='chord'>H7</span>Götter lachen sich<span class='chord'>Em</span> krumm</p>
<p class='song show-chords'>Wenn ihr <span class='chord'>H7</span>das Welt nennt, bin ich <span class='chord'>Em</span>gern weltfremd</p>
<p class='song show-chords'>Die<span class='chord'>Am</span> Götter lachen sich<span class='chord'>H7</span> krumm</p>
\
\
<p class='song show-chords'>Ihr T<span class='chord'>C</span>raumverkäufer, Sy<span class='chord'>G</span>mptomdesigner</p>
<p class='song show-chords'><span class='chord'>H7</span>Merkt ihr noch, was pass<span class='chord'>Em</span>iert? </p>
<p class='song show-chords'><span class='chord'>C</span>Wer hat euch das Land und das <span class='chord'>G</span>Wasser geschenkt, </p>
<p class='song show-chords'>Das ihr <span class='chord'>H7</span>jetzt privatis<span class='chord'>Em</span>iert</p>
<p class='song show-chords'>Ihr H<span class='chord'>C</span>euchler, ihr Lügner, ihr<span class='chord'>G</span> Rattenfänger </p>
<p class='song show-chords'>Ihr <span class='chord'>H7</span>Wertpapierver<span class='chord'>Em</span>käufer</p>
<p class='song show-chords'>Man <span class='chord'>C</span>hat euch Geist und Ge<span class='chord'>G</span>fühl gegeben </p>
<p class='song show-chords'>Und <span class='chord'>H7</span>doch seid ihr nur Mit<span class='chord'>Em</span>läufer </p>
<p class='song show-chords'>Ihr g<span class='chord'>C</span>roßen, vernarbten,<span class='chord'>G</span> hilflosen Riesen </p>
<p class='song show-chords'>Ihr <span class='chord'>H7</span>wart doch auch mal <span class='chord'>Em</span>klein</p>
<p class='song show-chords'>Und <span class='chord'>C</span>jemand hat euch mit Sch<span class='chord'>G</span>weigen gestraft </p>
<p class='song show-chords'>Und <span class='chord'>H7</span>ließ euch darin al<span class='chord'>Em</span>lein </p>
<p class='song show-chords'>Und jetzt <span class='chord'>C</span>hört ihr nicht nur die<span class='chord'>G</span> Götter nicht lachen </p>
<p class='song show-chords'>Ihr <span class='chord'>H7</span>hört auch ihr die Kinder nicht<span class='chord'>Em</span> weinen</p>
<p class='song show-chords'>Und <span class='chord'>C</span>sagt ihnen weiter, es <span class='chord'>G</span>würde nicht wehtun</p>
<p class='song show-chords'><span class='chord'>H7</span>  Ohne es so zu <span class='chord'>Em</span>meinen</p>
<p class='song show-chords'>Macht <span class='chord'>C</span>ihr ruhig Pläne<span class='chord'>G</span>, ich steh am Rand </p>
<p class='song show-chords'>Ich <span class='chord'>H7</span>sehe euch und ich bin nicht al<span class='chord'>Em</span>lein </p>
<p class='song show-chords'>Hinter <span class='chord'>C</span>mir stehen mehr und mehr <span class='chord'>G</span>Weltfremde </p>
<p class='song show-chords'>Die <span class='chord'>H7</span>passen auch nicht hin<span class='chord'>Em</span>ein </p>
\
<p class='song show-chords'>Und jetzt <span class='chord'>C</span>wartet nicht auf ein ver<span class='chord'>G</span>söhnliches Ende </p>
<p class='song show-chords'>D<span class='chord'>H7</span>en Gefallen tu ich euch <span class='chord'>Em</span>nicht </p>
<p class='song show-chords'>Kein<span class='chord'>C</span> Augenzwinkern, keine <span class='chord'>G</span>milde Pointe,</p>
<p class='song show-chords'>Die das <span class='chord'>H7</span>Unwohlsein wieder b<span class='chord'>Em</span>richt</p>
<p class='song show-chords'>Irgend<span class='chord'>C</span>wann werden die Götter<span class='chord'>G</span> nicht mehr lachen </p>
<p class='song show-chords'>Und<span class='chord'>H7</span> falls es mich dann nicht mehr <span class='chord'>Em</span>gibt </p>
<p class='song show-chords'>Hinterl<span class='chord'>C</span>ass ich ein Kind, das sich s<span class='chord'>G</span>elbst gehört</p>
<p class='song show-chords'><span class='chord'>H7</span>   Und dies unhandliche Lied<span class='chord'>Em</span></p>
   \
\
\
