## S'Nüüni Tramm - Mani Matter
\
```{}
|Am_______|________|________|________|\
|_________|________|________|________|\
|G7_______|________|________|________|\
|Am_______|________|E_______|Am6+____|\
```
\
Geschter z'Nacht het ds Nüünitram statt hei i ds Depot z'gah\
Plötzlich, niemer weis warum, sys Schinegleis verla\
Isch zum Himel ufegflogen und dert natina\
I dr Nacht verschwunden ohni Spure z'hinderla\
\
Sibe Hünd hei kläglich gjoulet grad wo das isch gscheh\
Und e chalte Windstoss isch dür d'Monbijou-Allee\
Und s'het e Betrunkne wos als einzige het gseh\
Dür die lääare Strasse brüelet: Oherjeminee!\
\
Das het amne Polizischt wo dert zur Stell isch gsy\
Hüenerhut ygjagt, dass är es Ei het gleit derby\
Und e Frou het tänkt: Wie nützlech doch die Tschugger sy!\
Het ds Ei gno und's bräglet bis's es Stierenoug isch gsy\
\
Doch dr Stier isch us dr Pfanne drusbrönnt und dervo\
D'Frou het afa brüele, lut und Zetermordio\
Bis dr Stier sech in es Tram verwandlet het und so\
Uf de Gleis isch wytergfahre gäge ds Tramdepot\
\
Druf ischs wider stiller worden und de schliesslech Rue\
Ds Nüünitram isch hinden um e Rank em Depot zue\
Eine het no grüeft: I pfuuse, blaset mir id Schue!\
Und dir heit jitz vo mym Gschichtli sicher alli gnue\
\
\
