## Am Weihnachtsbaum die Lichter brennen
\
\
<p class='song show-chords'><span class='chord'>G</span>                    <span class='chord'>C</span>      <span class='chord'>G</span></p>
<p class='song show-chords'><span class='chord'>Am</span>eihnachtsbaume die Lichter brennen,</p>
<p class='song show-chords'>Wie glänzt er<span class='chord'>Am</span> festlich,<span class='chord'>D</span> lieb und<span class='chord'>G</span> mild,</p>
<p class='song show-chords'><span class='chord'>G</span>Als spräch’ e<span class='chord'>D</span>r: wollt in mir<span class='chord'>G</span> erkennen</p>
<p class='song show-chords'>Getreuer <span class='chord'>D</span>Hoffnung s<span class='chord'>D7</span>tilles <span class='chord'>G</span>Bild.</p>
\
\
<p class='song show-chords'><span class='chord'>G</span>Die Kinder stehn mit <span class='chord'>C</span>hellen B<span class='chord'>G</span>licken,</p>
<p class='song show-chords'>Das Auge <span class='chord'>Am</span>lacht, es <span class='chord'>D</span>lacht das <span class='chord'>G</span>Herz;</p>
<p class='song show-chords'><span class='chord'>G</span>O fröhlich, <span class='chord'>D</span>seliges Ent<span class='chord'>G</span>zücken!</p>
<p class='song show-chords'>Die Alten sc<span class='chord'>D</span>hauen <span class='chord'>D7</span>himmel<span class='chord'>G</span>wärts.</p>
\
\
<p class='song show-chords'>Z<span class='chord'>G</span>wei Engel sind he<span class='chord'>C</span>reinget<span class='chord'>G</span>reten,</p>
<p class='song show-chords'>Kein Auge <span class='chord'>Am</span>hat sie <span class='chord'>D</span>kommen <span class='chord'>G</span>sehn,</p>
<p class='song show-chords'><span class='chord'>G</span>Sie gehn zum <span class='chord'>D</span>Weihnachtstisch und <span class='chord'>G</span>beten,</p>
<p class='song show-chords'>Und wenden <span class='chord'>D</span>wieder <span class='chord'>D7</span>sich und <span class='chord'>G</span>gehn</p>
 \
<p class='song show-chords'>G<span class='chord'>G</span>esegnet seid ihr <span class='chord'>C</span>alten L<span class='chord'>G</span>eute,</p>
<p class='song show-chords'>Gesegnet <span class='chord'>Am</span>sei du k<span class='chord'>D</span>leine Sc<span class='chord'>G</span>haar!</p>
<p class='song show-chords'><span class='chord'>G</span>Wir bringen <span class='chord'>D</span>Gottes Segen <span class='chord'>G</span>heute</p>
<p class='song show-chords'>Dem braunen, <span class='chord'>D</span>wie dem <span class='chord'>D7</span>weißen<span class='chord'>G</span> Haar!</p>
\
\
<p class='song show-chords'>Zu <span class='chord'>G</span>guten Menschen, <span class='chord'>C</span>die sich <span class='chord'>G</span>lieben,</p>
<p class='song show-chords'>Schickt<span class='chord'>Am</span> uns der <span class='chord'>D</span>Herr als <span class='chord'>G</span>Boten aus,</p>
<p class='song show-chords'><span class='chord'>G</span>Und seid Ihr t<span class='chord'>D</span>reu und fromm geb<span class='chord'>G</span>lieben,</p>
<p class='song show-chords'>Wir treten <span class='chord'>D</span>wieder<span class='chord'>D7</span> in dies <span class='chord'>G</span>Haus!</p>
 \
\
<p class='song show-chords'><span class='chord'>G</span>Kein Ohr hat ihren Sp<span class='chord'>C</span>ruch vern<span class='chord'>G</span>ommen,</p>
<p class='song show-chords'>Unsichtbar <span class='chord'>Am</span>jedes <span class='chord'>D</span>Menschen B<span class='chord'>G</span>lick,</p>
<p class='song show-chords'><span class='chord'>G</span>Sind sie ge<span class='chord'>D</span>gangen, wie ge<span class='chord'>G</span>kommen,</p>
<p class='song show-chords'>Doch Gottes <span class='chord'>D</span>Segen b<span class='chord'>D7</span>lieb zu<span class='chord'>G</span>rück!</p>
