## Süsser die Glocken nie klingen - 
\
<p class='song show-chords'>D<span class='chord'>G</span>A7<span class='chord'>D</span></p>
\
\
<p class='song show-chords'><span class='chord'>D</span>Süßer die Glocken n<span class='chord'>A</span>ie klingen</p>
<p class='song show-chords'><span class='chord'>A7</span>als zu der Weihnacht<span class='chord'>D</span>szeit.</p>
<p class='song show-chords'>S'ist als ob Engelein<span class='chord'>G</span> singen</p>
<p class='song show-chords'><span class='chord'>D</span>wieder von<span class='chord'>A7</span> Frieden und<span class='chord'>D</span> Freud'.</p>
<p class='song show-chords'><span class='chord'>A7</span>Wie sie g<span class='chord'>D</span>esungen in<span class='chord'>A7</span> seliger<span class='chord'>D</span> Nacht.</p>
<p class='song show-chords'><span class='chord'>A7</span>Wie sie g<span class='chord'>D</span>esungen in<span class='chord'>A7</span> seliger<span class='chord'>D</span> Nacht.</p>
<p class='song show-chords'>Glocken mit<span class='chord'>D7</span> heiligem<span class='chord'>G</span> Klang,</p>
<p class='song show-chords'><span class='chord'>D</span>klinget die<span class='chord'>A7</span> Erde en<span class='chord'>D</span>tlang!</p>
\
 \
<p class='song show-chords'><span class='chord'>D</span>Oh, wenn die Glocken e<span class='chord'>A</span>rklingen,</p>
<p class='song show-chords'><span class='chord'>A7</span>schnell sie das Christkindlein<span class='chord'>D</span> hört;</p>
<p class='song show-chords'>tut sich vom Himmel dann<span class='chord'>G</span> schwingen</p>
<p class='song show-chords'><span class='chord'>D</span>eilet he<span class='chord'>A7</span>rnieder zur<span class='chord'>D</span> Erd'.</p>
<p class='song show-chords'><span class='chord'>A7</span>Segnet den<span class='chord'>D</span> Vater, die<span class='chord'>A7</span> Mutter, das<span class='chord'>D</span> Kind.</p>
<p class='song show-chords'><span class='chord'>A7</span>Segnet den<span class='chord'>D</span> Vater, die<span class='chord'>A7</span> Mutter, das<span class='chord'>D</span> Kind.</p>
<p class='song show-chords'>Glocken mit<span class='chord'>D7</span> heiligem<span class='chord'>G</span> Klang,</p>
<p class='song show-chords'><span class='chord'>D</span>klinget die<span class='chord'>A7</span> Erde en<span class='chord'>D</span>tlang!</p>
\
\
<p class='song show-chords'><span class='chord'>D</span>Klinget mit lieblichem<span class='chord'>A</span> Schalle</p>
<p class='song show-chords'><span class='chord'>A7</span>über die Meere noc<span class='chord'>D</span>h weit,</p>
<p class='song show-chords'>daß sich erfreuen doc<span class='chord'>G</span>h alle</p>
<p class='song show-chords'><span class='chord'>D</span>seliger<span class='chord'>A7</span> Weihnacht<span class='chord'>D</span>szeit.</p>
<p class='song show-chords'><span class='chord'>A7</span>Alle au<span class='chord'>D</span>fjauchzen mit<span class='chord'>A7</span> einem G<span class='chord'>D</span>esang.</p>
<p class='song show-chords'><span class='chord'>A7</span>Alle au<span class='chord'>D</span>fjauchzen mit<span class='chord'>A7</span> einem G<span class='chord'>D</span>esang.</p>
<p class='song show-chords'>Glocken mit<span class='chord'>D7</span> heiligem<span class='chord'>G</span> Klang,</p>
<p class='song show-chords'><span class='chord'>D</span>klinget die<span class='chord'>A7</span> Erde en<span class='chord'>D</span>tlang!</p>
\
