## Marys Bornchild
\
<p class='song show-chords'><span class='chord'>G</span>Long time ago in<span class='chord'>C</span> Bethl<span class='chord'>Am</span>ehem, so the<span class='chord'>D</span> Holy Bible<span class='chord'>G</span> says,  </p>
<p class='song show-chords'><span class='chord'>G</span>Mary's boychild,<span class='chord'>C</span> Jesus<span class='chord'>Am</span> Christ, was<span class='chord'>G</span> born on<span class='chord'>D</span> Christmas<span class='chord'>G</span> Day. </p>
\
**Chorus:**\
<p class='song show-chords'><span class='chord'>G</span>Hark now!<span class='chord'>C</span> Hear the<span class='chord'>D</span> Angels<span class='chord'>G</span> sing, a<span class='chord'>Em</span> King was<span class='chord'>Am</span> born t<span class='chord'>D</span>oday, </p>
<p class='song show-chords'>and<span class='chord'>G</span> man will live fo<span class='chord'>C</span>rever<span class='chord'>Am</span> more b<span class='chord'>G</span>ecause of<span class='chord'>D</span> Christmas<span class='chord'>G</span> Day. </p>
\
\
<p class='song show-chords'><span class='chord'>G</span>While shepherds watch their<span class='chord'>C</span> flocks by<span class='chord'>Am</span> night, </p>
<p class='song show-chords'>they see a<span class='chord'>D</span> bright new shining<span class='chord'>G</span> star. </p>
<p class='song show-chords'>They hear a choir<span class='chord'>C</span> sing a<span class='chord'>Am</span> song,  </p>
<p class='song show-chords'>the music<span class='chord'>G</span> seemed to<span class='chord'>D</span> come from <span class='chord'>G</span>afar.  </p>
  \
{chorus} \
\
<p class='song show-chords'><span class='chord'>G</span>Now Joseph and his<span class='chord'>C</span> wife,<span class='chord'>Am</span> Mary, came to<span class='chord'>D</span> Bethlehem that<span class='chord'>G</span> night. </p>
<p class='song show-chords'><span class='chord'>G</span>They found no place to<span class='chord'>C</span> bear the<span class='chord'>Am</span> child,  </p>
<p class='song show-chords'>not a<span class='chord'>G</span> single<span class='chord'>D</span> room was in<span class='chord'>G</span> sight.      </p>
  \
{chorus}\
\
<p class='song show-chords'><span class='chord'>G</span>Trumpets<span class='chord'>C</span> sound and<span class='chord'>D</span> Angels<span class='chord'>G</span> sing..<span class='chord'>Em</span>.listen to<span class='chord'>Am</span> what they<span class='chord'>D</span> say, </p>
<p class='song show-chords'><span class='chord'>D</span>that<span class='chord'>G</span> man will live fo<span class='chord'>C</span>rever<span class='chord'>Am</span> more b<span class='chord'>G</span>ecause of<span class='chord'>D</span> Christmas<span class='chord'>G</span> Day. </p>
\
{chorus}\
{chorus}\
  \
<p class='song show-chords'><span class='chord'>G</span>And then they found a<span class='chord'>C</span> little<span class='chord'>Am</span> nook, in a<span class='chord'>D</span> stable all fo<span class='chord'>G</span>rlorn. </p>
<p class='song show-chords'><span class='chord'>G</span>And in a manger,<span class='chord'>C</span> cold and<span class='chord'>Am</span> dark, Mary's<span class='chord'>G</span> little<span class='chord'>D</span> boy was<span class='chord'>G</span> born.</p>
\
<p class='song show-chords'><span class='chord'>G</span>Long time ago in<span class='chord'>C</span> Bethl<span class='chord'>Am</span>ehem, so the<span class='chord'>D</span> Holy Bible<span class='chord'>G</span> says,  </p>
<p class='song show-chords'><span class='chord'>G</span>Mary's boychild,<span class='chord'>C</span> Jesus<span class='chord'>Am</span> Christ, was<span class='chord'>G</span> born on<span class='chord'>D</span> Christmas<span class='chord'>G</span> Day. </p>
\
  \
{chorus}\
\
<p class='song show-chords'><span class='chord'>G</span>Trumpets<span class='chord'>C</span> sound and<span class='chord'>D</span> Angels<span class='chord'>G</span> sing..<span class='chord'>Em</span>.listen to<span class='chord'>Am</span> what they<span class='chord'>D</span> say, </p>
<p class='song show-chords'><span class='chord'>D</span>that<span class='chord'>G</span> man will live fo<span class='chord'>C</span>rever<span class='chord'>Am</span> more b<span class='chord'>G</span>ecause of<span class='chord'>D</span> Christmas<span class='chord'>G</span> Day.</p>
