## Silent Night
\
<p class='song show-chords'><span class='chord'>G</span>Silent night! Holy night!<span class='chord'>D</span> All is c<span class='chord'>D7</span>alm a<span class='chord'>G</span>ll is<span class='chord'>G7</span> bright </p>
<p class='song show-chords'><span class='chord'>C</span>Round yon virgin<span class='chord'>G</span> mother and child<span class='chord'>C</span> Holy infant so<span class='chord'>G</span> tender and mild </p>
<p class='song show-chords'><span class='chord'>D</span>Sleep in<span class='chord'>D7</span> heavenly p<span class='chord'>G</span>eace! Sl<span class='chord'>G</span>eep in h<span class='chord'>D</span>eavenly pe<span class='chord'>G</span>ace!</p>
\
<p class='song show-chords'><span class='chord'>G</span>Silent night! Holy night! <span class='chord'>D</span>Shepherds<span class='chord'>D7</span> quake a<span class='chord'>G</span>t the <span class='chord'>G7</span>sight</p>
<p class='song show-chords'><span class='chord'>C</span>Glories stream from<span class='chord'>G</span> heaven afar<span class='chord'>C</span> Heavenly hosts sing<span class='chord'>G</span> Hallelujah</p>
<p class='song show-chords'><span class='chord'>D</span>Christ the<span class='chord'>D7</span> Saviour is b<span class='chord'>G</span>orn! C<span class='chord'>G</span>hrist the S<span class='chord'>D</span>aviour is b<span class='chord'>G</span>orn!</p>
\
<p class='song show-chords'><span class='chord'>G</span>Silent night! Holy night!<span class='chord'>D</span> Son of<span class='chord'>D7</span> God l<span class='chord'>G</span>ove's pure <span class='chord'>G7</span>light </p>
<p class='song show-chords'><span class='chord'>C</span>Radiant beams from<span class='chord'>G</span> thy holy face<span class='chord'>C</span> With the dawn of re<span class='chord'>G</span>deeming grace</p>
<p class='song show-chords'><span class='chord'>D</span>Jesus<span class='chord'>D7</span> lord at thy b<span class='chord'>G</span>irth! J<span class='chord'>G</span>esus l<span class='chord'>D</span>ord at thy b<span class='chord'>G</span>irth! </p>
\
\
Stille Nacht! Heilige Nacht!\
Alles schläft, einsam wacht\
nur das traute hoch heilige Paar.\
"Holder Knabe im lockigen Haar\
schlaf in himmlischer Ruh'\
schlaf in himmlischer Ruh'!\
\
Stille Nacht! Heilige Nacht!\
Hirten erst, kundgemacht!\
durch der Engel Halleluja\
tönt es laut von Fern' und Nah:\
Christ, der Retter ist da!\
Christ, der Retter ist da!\
\
Stille Nacht! Heilige Nacht!\
Gottes Sohn, o wie lacht\
lieb' aus deinem göttlichen Mund\
da uns schlägt die rettende Stund':\
Christ in deiner Geburt.\
Christ in deiner Geburt.\
\
