## Dance me to the end of Love - Leonard Cohan
\
<p class='song show-chords'><span class='chord'>Am</span>Dance me to your beauty with a<span class='chord'>Em</span> burning violin</p>
<p class='song show-chords'><span class='chord'>Am</span>Dance me through the panic 'til I'm<span class='chord'>Em</span> gathered safely in</p>
<p class='song show-chords'><span class='chord'>Am</span>Lift me like an olive branch and<span class='chord'>Em</span> be my homeward dove</p>
<p class='song show-chords'><span class='chord'>B7</span>Dance me to the end <span class='chord'>Em</span>of love</p>
<p class='song show-chords'><span class='chord'>B7</span>Dance me to the end <span class='chord'>Em</span>of love</p>
\
Oh let me see your beauty when the witnesses are gone \
Let me feel you moving like they do in Babylon \
Show me slowly what I only know the limits of \
Dance me to the end of love \
Dance me to the end of love \
\
Dance me to the wedding now, dance me on and on \
Dance me very tenderly and dance me very long \
We're both of us beneath our love, we're both of us above \
Dance me to the end of love \
Dance me to the end of love\
\
Dance me to your beauty with a burning violin \
Dance me through the panic till I'm gathered safely in \
Touch me with your naked hand or touch me with your glove \
Dance me to the end of love (3x)\
\
{comment: play intro again}\
\
