## Ein Bett im Kornfeld - Jürgen Drews
\
<p class='song show-chords'><span class='chord'>D</span>Sommerabend über blühendem Land.</p>
Schon seit Mittag stand ich am \
Straßenrand.\
<p class='song show-chords'>Bei jedem W<span class='chord'>A</span>agen, der vorüber fuhr,</p>
<p class='song show-chords'>hob ich den <span class='chord'>D</span>Daumen.</p>
auf einem Fahrrad kam da ein \
Mädchen her.\
Und sie sagte: "Ich bedaure dich sehr."\
<p class='song show-chords'>Doch ich l<span class='chord'>A</span>achte und sprach: "Ich brauch keine weichen <span class='chord'>D</span>Daunen"</p>
\
**Chorus:**\
<p class='song show-chords'>Ein Bett im K<span class='chord'>G</span>ornfeld,</p>
Das ist immer frei, denn es ist\
<p class='song show-chords'><span class='chord'>D</span>Sommer, und was ist schon dabei.</p>
<p class='song show-chords'>Die Grillen <span class='chord'>A</span>singen und es duftet </p>
<p class='song show-chords'>nach Heu, wenn ich <span class='chord'>D</span>träume.</p>
<p class='song show-chords'>Ein Bett im K<span class='chord'>G</span>ornfeld, zwischen </p>
Blumen und Stroh,\
<p class='song show-chords'>Und die S<span class='chord'>D</span>terne leuchten mir sowieso</p>
<p class='song show-chords'>Ein Bett im K<span class='chord'>A</span>ornfeld mach ich mir </p>
<p class='song show-chords'>irgendwo ganz a<span class='chord'>D</span>lleine.</p>
\
\
\
<p class='song show-chords'><span class='chord'>D</span>Etwas später lag ihr Fahrrad im </p>
Gras, Und so kam es, dass sie die \
Zeit vergass,\
<p class='song show-chords'>Mit der G<span class='chord'>A</span>itarre hab ich ihr erzählt</p>
<p class='song show-chords'>Von meinem <span class='chord'>D</span>Leben.</p>
Auf einmal rief sie\
"Es ist höchste Zeit, Schon ist es \
dunkel und mein Weg ist noch Weit"\
<p class='song show-chords'>Doch ich l<span class='chord'>A</span>achte und sprach:</p>
<p class='song show-chords'>"Ich hab dir noch viel zu g<span class='chord'>D</span>eben".</p>
\
{chorus}\
\
\
