## Eskimo - Mani Matter
\
<p class='song show-chords'><span class='chord'>Am</span>Kenned ihr das Gschichtli scho<span class='chord'>E</span> vu dem arme<span class='chord'>Am</span> Eskimo,</p>
<p class='song show-chords'><span class='chord'>Em</span>wo in<span class='chord'>Am</span> Grönlan<span class='chord'>Em</span>d einisc<span class='chord'>Am</span>h so <span class='chord'>Em</span>  truuri<span class='chord'>Am</span>g isch um<span class='chord'>Em</span>s Leb<span class='chord'>Am</span>e cho.</p>
\
<p class='song show-chords'><span class='chord'>Am</span>Er hät dank em Radi<span class='chord'>E</span>o freud ar Musi<span class='chord'>Am</span>g übercho</p>
<p class='song show-chords'><span class='chord'>Em</span>und het<span class='chord'>Am</span> denkt das<span class='chord'>Em</span> chan i<span class='chord'>Am</span> o  <span class='chord'>Em</span> so isch<span class='chord'>Am</span> er is<span class='chord'>Em</span> unglüc<span class='chord'>Am</span>k cho.</p>
\
<p class='song show-chords'><span class='chord'>Am</span>Nämlich hät er sich für <span class='chord'>E</span>zwo Fläsche <span class='chord'>Am</span>Lebertran es no</p>
<p class='song show-chords'><span class='chord'>Em</span>guet e<span class='chord'>Am</span>rhatlnigs<span class='chord'>Em</span> Cemab<span class='chord'>Am</span>lo   <span class='chord'>Em</span> kouft und<span class='chord'>Am</span> hets i d<span class='chord'>Em</span> höl<span class='chord'>Am</span>i gno.</p>
\
<p class='song show-chords'><span class='chord'>Am</span>Doch won er fortissimio<span class='chord'>E</span> gspilt het uf sim<span class='chord'>Am</span> Cembalo</p>
<p class='song show-chords'><span class='chord'>Em</span>isch en<span class='chord'>Am</span> Iisbä<span class='chord'>Em</span>r in<span class='chord'>Am</span>e cho un<span class='chord'>Em</span>d het n<span class='chord'>Am</span>e zwüsche<span class='chord'>Em</span> d chral<span class='chord'>Am</span>le gno.</p>
\
<p class='song show-chords'><span class='chord'>Am</span>                       <span class='chord'>E</span>            <span class='chord'>Am</span></p>
<p class='song show-chords'><span class='chord'>D</span>unst isch geng es Risiko so isch er ums Lebe cho</p>
<p class='song show-chords'><span class='chord'>Em</span>und das<span class='chord'>Am</span> isch d<span class='chord'>Em</span> Moral de<span class='chord'>Am</span>rvo <span class='chord'>Em</span> choufed<span class='chord'>Am</span> nie es<span class='chord'>Em</span> Cemb<span class='chord'>Am</span>alo</p>
<p class='song show-chords'><span class='chord'>Em</span>süscht geit<span class='chord'>Am</span>s euch gra<span class='chord'>Em</span>d ebeso<span class='chord'>Em</span>  wie de<span class='chord'>Am</span>m arm<span class='chord'>Em</span>e Es<span class='chord'>Am</span>kimo</p>
<p class='song show-chords'><span class='chord'>Em</span>wo in<span class='chord'>Am</span> Grönlan<span class='chord'>Em</span>d einisc<span class='chord'>Am</span>h so<span class='chord'>Em</span>  truuri<span class='chord'>Am</span>g isch um<span class='chord'>Em</span>s leb<span class='chord'>Am</span>e cho.</p>
\
\
