## Heute hier morgen Dort - Hannes Wader
\
<p class='song show-chords'>Heute<span class='chord'>G</span> hier, morgen dort bin kaum<span class='chord'>C</span> da muß ic<span class='chord'>G</span>h fort</p>
<p class='song show-chords'>hab mich niemals des <span class='chord'>Em</span>wegen be<span class='chord'>D</span>klagt</p>
<p class='song show-chords'>hab es <span class='chord'>G</span>selbst so gewählt nie die<span class='chord'>C</span> Jahre ge<span class='chord'>G</span>zählt</p>
<p class='song show-chords'>nie nach <span class='chord'>Em</span>gestern und<span class='chord'>D</span> morgen <span class='chord'>G</span>gefragt</p>
\
**Chorus:**\
<p class='song show-chords'>Manchmal t<span class='chord'>D</span>räume ich schwer und dan<span class='chord'>C</span>n denk` ich e<span class='chord'>G</span>s wär</p>
<p class='song show-chords'>Zeit zu b<span class='chord'>D</span>leiben und nun was ganz<span class='chord'>C</span> andres zu<span class='chord'>G</span> tun</p>
<p class='song show-chords'>So vergeht Jahr um Jahr und<span class='chord'>C</span> ist mir längs<span class='chord'>G</span>t klar</p>
<p class='song show-chords'>daß nicht<span class='chord'>Em</span>s bleibt, daß nich<span class='chord'>D</span>ts bleibt wie <span class='chord'>G</span>es war.</p>
\
\
\
<p class='song show-chords'>Daß ma<span class='chord'>G</span>n mich kaum vermißt schon na<span class='chord'>C</span>ch Tagen <span class='chord'>G</span>vergißt</p>
<p class='song show-chords'>wenn ich längst wiede<span class='chord'>Em</span>r anders w<span class='chord'>D</span>o bin</p>
<p class='song show-chords'>stört un<span class='chord'>G</span>d kümmert mich nicht vielleic<span class='chord'>C</span>ht bleibt mei<span class='chord'>G</span>n Gesicht</p>
<p class='song show-chords'>doch dem<span class='chord'>Em</span> ein oder<span class='chord'>D</span> andern im <span class='chord'>G</span>Sinn</p>
\
{chorus}\
\
<p class='song show-chords'>Fragt mich<span class='chord'>G</span> einer warum ich so<span class='chord'>C</span> bin bleib ich s<span class='chord'>G</span>tumm</p>
<p class='song show-chords'>denn die Antwort d<span class='chord'>Em</span>arauf fällt mi<span class='chord'>D</span>r schwer</p>
<p class='song show-chords'>denn was<span class='chord'>G</span> neu ist wird alt und was <span class='chord'>C</span>gestern noch<span class='chord'>G</span> galt</p>
<p class='song show-chords'>stimmt schon<span class='chord'>Em</span> heut oder m<span class='chord'>D</span>orgen nicht <span class='chord'>G</span>mehr.</p>
\
<p class='song show-chords'>Manchmal tr<span class='chord'>D</span>äume ich schwer und dann<span class='chord'>C</span> denk ich es <span class='chord'>G</span>wär</p>
<p class='song show-chords'>Zeit zu b<span class='chord'>D</span>leiben und nun was ganz<span class='chord'>C</span> andres zu<span class='chord'>G</span> tun</p>
<p class='song show-chords'>So vergeht Jahr um Jahr und<span class='chord'>C</span> ist mir längs<span class='chord'>G</span>t klar</p>
<p class='song show-chords'>daß nicht<span class='chord'>Em</span>s bleibt, daß nich<span class='chord'>D</span>ts bleibt wie <span class='chord'>G</span>es war.</p>
