## Ihr Kinderlein Kommet - 
\
<p class='song show-chords'>Ihr<span class='chord'>G</span> Kinderlein kommet, oh<span class='chord'>D7</span> kommet doch<span class='chord'>G</span> all!</p>
<p class='song show-chords'>Zur Krippe her kommet in<span class='chord'>D7</span> Bethlehems<span class='chord'>G</span> Stall,</p>
<p class='song show-chords'>und<span class='chord'>D7</span> seht, was in dieser ho<span class='chord'>G</span>chheiligen<span class='chord'>C</span> Nacht</p>
<p class='song show-chords'>der<span class='chord'>G</span> Vater im Himmel fü<span class='chord'>D7</span>r Freude un<span class='chord'>G</span>s macht.</p>
\
<p class='song show-chords'>O<span class='chord'>G</span> seht in der Krippe im<span class='chord'>D7</span> nächtliche<span class='chord'>G</span>n Stall,</p>
<p class='song show-chords'>seht hier bei des Lichtes hel<span class='chord'>D7</span>lglänzende<span class='chord'>G</span>m Strahl,</p>
<p class='song show-chords'>in<span class='chord'>D7</span> reinlichen Windeln das<span class='chord'>G</span> himmlische<span class='chord'>C</span> Kind,</p>
<p class='song show-chords'>viel<span class='chord'>G</span> schöner und holder al<span class='chord'>D7</span>s Engelei<span class='chord'>G</span>n sind.</p>
\
<p class='song show-chords'>Da<span class='chord'>G</span> liegt es, das Kindlein,au<span class='chord'>D7</span>f Heu und au<span class='chord'>G</span>f Stroh,</p>
<p class='song show-chords'>Maria und Josef b<span class='chord'>D7</span>etrachten es<span class='chord'>G</span> froh.</p>
<p class='song show-chords'>Die<span class='chord'>D7</span> redlichen Hirten knien<span class='chord'>G</span> betend d<span class='chord'>C</span>avor,</p>
<p class='song show-chords'>hoch<span class='chord'>G</span> oben schwebt jubelnd der<span class='chord'>D7</span> Engelein<span class='chord'>G</span> Chor.</p>
\
<p class='song show-chords'>O<span class='chord'>G</span> beugt wie die Hirten a<span class='chord'>D7</span>nbetend die<span class='chord'>G</span> Knie;</p>
<p class='song show-chords'>erhebet die Hände un<span class='chord'>D7</span>d danket wi<span class='chord'>G</span>e sie!</p>
<p class='song show-chords'>Stimmt<span class='chord'>D7</span> freudig, ihr Kinder, wer<span class='chord'>G</span> sollt' sich nicht<span class='chord'>C</span> freun?</p>
<p class='song show-chords'>Stimmt<span class='chord'>G</span> freudig zum Jubel der<span class='chord'>D7</span> Engel mit<span class='chord'>G</span> ein!</p>
\
<p class='song show-chords'>Was<span class='chord'>G</span> geben wir Kinder,was<span class='chord'>D7</span> schenken wir<span class='chord'>G</span> dir,</p>
<p class='song show-chords'>Du bestes und liebstes der<span class='chord'>D7</span> Kinder, d<span class='chord'>G</span>afür?</p>
<p class='song show-chords'>Nichts<span class='chord'>D7</span> willst du von Schätzen un<span class='chord'>G</span>d Reichtum de<span class='chord'>C</span>r Welt,</p>
<p class='song show-chords'>Ein<span class='chord'>G</span> Herz nur voll Demut a<span class='chord'>D7</span>llein dir g<span class='chord'>G</span>efällt.</p>
\
