## Jar of Hearts - Christina Perri
\
<p class='song show-chords'><span class='chord'>Bm</span>I know I can't take one more <span class='chord'>D</span>step towards you</p>
<p class='song show-chords'><span class='chord'>A</span>'Cause all thats waiting is re<span class='chord'>Em</span>gret</p>
<p class='song show-chords'><span class='chord'>Bm</span>And don't you know I'm not your <span class='chord'>D</span>ghost anymore</p>
<p class='song show-chords'><span class='chord'>A</span>You lost the love I loved the <span class='chord'>G</span>most</p>
<p class='song show-chords'><span class='chord'>Em</span>I learned to live <span class='chord'>D</span>half a <span class='chord'>A</span>life</p>
<p class='song show-chords'><span class='chord'>Em</span>And now you <span class='chord'>D</span>want me one more time<span class='chord'>A</span></p>
\
**Chorus:**\
<p class='song show-chords'><span class='chord'>D</span>Who do you think you <span class='chord'>A</span>are?</p>
<p class='song show-chords'>Running 'round leaving <span class='chord'>Bm</span>scars</p>
<p class='song show-chords'>Collecting a jar of h<span class='chord'>G</span>earts</p>
<p class='song show-chords'>Tearing love a<span class='chord'>D</span>part</p>
<p class='song show-chords'><span class='chord'>D</span>You're gonna catch a <span class='chord'>A</span>cold</p>
<p class='song show-chords'>From the ice inside your <span class='chord'>Bm</span>soul</p>
<p class='song show-chords'>Don't come back for <span class='chord'>G</span>me</p>
<p class='song show-chords'>Who do you think you <span class='chord'>D</span>are?</p>
\
\
\
<p class='song show-chords'><span class='chord'>Bm</span>I hear you're asking all a<span class='chord'>D</span>round</p>
<p class='song show-chords'><span class='chord'>A</span>If I am anywhere to be f<span class='chord'>Em</span>ound</p>
<p class='song show-chords'><span class='chord'>Bm</span>But I have grown too s<span class='chord'>D</span>trong</p>
<p class='song show-chords'><span class='chord'>A</span>To ever fall back in your <span class='chord'>G</span>arms</p>
<p class='song show-chords'><span class='chord'>Em</span>I've learned to live <span class='chord'>D</span>half a <span class='chord'>A</span>life</p>
<p class='song show-chords'><span class='chord'>Em</span>And now you <span class='chord'>D</span>want me one more tim<span class='chord'>A</span>e</p>
\
{chorus}\
\
<p class='song show-chords'><span class='chord'>Bm</span>It took so long just to <span class='chord'>D</span>feel alr<span class='chord'>E</span>ight</p>
<p class='song show-chords'>R<span class='chord'>Bm</span>emember how to put back the l<span class='chord'>D</span>ight in my <span class='chord'>E</span>eyes</p>
<p class='song show-chords'>I <span class='chord'>Bm</span>wish I had missed the first <span class='chord'>D</span>time that we k<span class='chord'>E</span>issed</p>
<p class='song show-chords'>'Cause <span class='chord'>Bm</span>you broke all your <span class='chord'>D</span>promis<span class='chord'>E</span>es</p>
<p class='song show-chords'>And <span class='chord'>G</span>now you're back</p>
                 F#\
You don't get to get me back\
\
{chorus}\
\
{comment: (...Don't come back at all) x2}\
\
<p class='song show-chords'>Who do you think you a<span class='chord'>D</span>re?</p>
<p class='song show-chords'>Who do you think you a<span class='chord'>D</span>re?</p>
<p class='song show-chords'>Who do you think you a<span class='chord'>D</span>re? </p>
