## Kaspar - Reinhard Mey
\
<p class='song show-chords'><span class='chord'>E</span>A<span class='chord'>D</span><span class='chord'>G</span> <span class='chord'>B</span><span class='chord'>E</span></p>
\
<p class='song show-chords'>Sie<span class='chord'>Am</span> sagten, er kaeme von <span class='chord'>D</span>Nuernberg her,</p>
<p class='song show-chords'>und er <span class='chord'>Am</span>spraeche kein Wort.</p>
<p class='song show-chords'>Auf dem <span class='chord'>Am</span>Marktplatz standen si<span class='chord'>D</span>e um ihn her</p>
<p class='song show-chords'>und be<span class='chord'>Am</span>gafften ihn dort.</p>
<p class='song show-chords'>Die<span class='chord'>C</span> einen raunten: Er ist ein Tier<span class='chord'>Am</span>!",  </p>
<p class='song show-chords'>die andern<span class='chord'>Am</span> fragten: Was will der hier?",</p>
<p class='song show-chords'><span class='chord'>D</span>und dass er sich doch zum <span class='chord'>G</span>Teufel scher'.</p>
<p class='song show-chords'>So j<span class='chord'>C</span>agt ihn doch fort, so ja<span class='chord'>Am</span>gt ihn doch fort!"</p>
\
Sein Haar in Straehnen und wirre,\
sein Gang war gebeugt.\
Seht, dieser arme Irre\
ward vom Teufel gezeugt.\
"Der Pfarrer reichte ihm einen Krug\
voll Milch, er sog in einem Zug.\
Der trinkt nicht vom Geschirre,\
den hat die Woelfin gesaugt,\
den hat die Woelfin gesaugt!"\
\
Mein Vater, der in uns'rem Orte\
Schulmeister war,\
trat zu ihm hin, trotz boeser Worte\
rings aus der Schar.\
Er sprach zu ihm ganz ruhig, und\
der Stumme oeffnete den Mund\
und stammelte die Worte:\
Heisse Kaspar, heisse Kaspar".\
\
Mein Vater brachte ihn mit nach Haus:\
Heisse Kaspar".\
Meine Mutter wusch seine Kleider aus\
und schnitt ihm das Haar.\
Sprechen lehrte mein Vater ihn,\
lesen und schreiben, und es schien,\
was man ihn lehrte, sog er in sich auf -\
wie gierig er war, wie gierig er war!\
\
Zur Schule gehoerte derzeit\
noch das Uttinger Feld,\
Kaspar und ich, wir pflegten zu zweit,\
bald war alles bestellt;\
wie hegten und pflegten jeden Keim,\
brachten im Herbst die Ernte ein,\
von den Leuten vermaledeit,\
von ihren Hunden verbellt,\
von ihren Hunden verbellt.\
\
Ein Wintertag, der Schnee lag frisch,\
es war Januar.\
Meine Mutter rief uns: Kommt zu Tisch,\
das Essen ist gar!"\
Mein Vater sagte: ...Appetit",\
ich wartete auf Kaspars Schritt.\
Mein Vater fragte mrrisch:\
Wo bleibt Kaspar, wo bleibt Kaspar?"\
\
Wir suchten, und wir fanden ihn\
auf dem Pfad bei dem Feld.\
Der Neuschnee wehte ueber ihn,\
sein Gesicht war entstellt,\
die Augen angstvoll aufgerissen,\
sein Hemd war blutig und zerschlissen.\
Erstochen hatten sie ihn,\
dort am Uttinger Feld, dort am Uttinger Feld!\
\
Der Polizeirat aus der Stadt\
fuellte ein Formular.\
Gott nehm' ihn hin in seiner Gnad"',\
sagte der Herr Vikar.\
Das Uttinger Feld liegt lang schon brach,\
nur manchmal bell'n mir noch die Hunde nach,\
dann streu' ich ein paar Blumen auf den Pfad\
fuer Kaspar, fuer Kaspar. \
\
