## New Slang - The Shins
\
<p class='song show-chords'><span class='chord'>Intro</span></p>
<p class='song show-chords'>Am<span class='chord'>C</span>F<span class='chord'>C</span>G<span class='chord'>C</span>Am<span class='chord'>G</span>x4</p>
<p class='song show-chords'><span class='chord'>C</span></p>
\
<p class='song show-chords'><span class='chord'>Am</span>Gold teeth and a<span class='chord'>C</span> curse for this<span class='chord'>F</span> town</p>
<p class='song show-chords'><span class='chord'>C</span>Were all in my<span class='chord'>G</span> mouth</p>
<p class='song show-chords'>Only<span class='chord'>C</span> I don't know<span class='chord'>F</span> how they got<span class='chord'>Am</span> out,<span class='chord'>G</span> dear</p>
<p class='song show-chords'><span class='chord'>Am</span>Turn me back i<span class='chord'>C</span>nto the<span class='chord'>F</span> pet</p>
<p class='song show-chords'><span class='chord'>C</span>I was when we<span class='chord'>G</span> met</p>
<p class='song show-chords'><span class='chord'>C</span>I was happier<span class='chord'>F</span> then with no<span class='chord'>Am</span> mind<span class='chord'>G</span> set</p>
\
**Chorus:**\
<p class='song show-chords'><span class='chord'>G</span>And if you'd a took to<span class='chord'>C</span> me like</p>
<p class='song show-chords'>A<span class='chord'>F</span> gull<span class='chord'>C</span> takes to the<span class='chord'>G</span> wind</p>
<p class='song show-chords'>Well, I'd a<span class='chord'>G</span> jumped from<span class='chord'>C</span> my tree</p>
<p class='song show-chords'>And<span class='chord'>F</span> I'd a<span class='chord'>C</span> danced like the<span class='chord'>F</span> king of the<span class='chord'>C</span> eyesores</p>
<p class='song show-chords'><span class='chord'>F</span>And the rest of our<span class='chord'>C</span> lives would'a<span class='chord'>G</span> fared well</p>
{end_of_chorus}\
\
<p class='song show-chords'><span class='chord'>Am</span>New slang when you<span class='chord'>C</span> notice the<span class='chord'>F</span> stripes</p>
<p class='song show-chords'><span class='chord'>C</span>The dirt in your<span class='chord'>G</span> fries</p>
<p class='song show-chords'>Hope<span class='chord'>C</span> it's right when you<span class='chord'>F</span> die</p>
<p class='song show-chords'>Old and<span class='chord'>Am</span> bo.<span class='chord'>G</span>.ny</p>
<p class='song show-chords'><span class='chord'>Am</span>Dawn breaks like a<span class='chord'>C</span> bull through the<span class='chord'>F</span> hall</p>
<p class='song show-chords'><span class='chord'>C</span>Never should'a<span class='chord'>G</span> called</p>
<p class='song show-chords'>But<span class='chord'>C</span> my heads to the<span class='chord'>F</span> wall</p>
<p class='song show-chords'>And I'm<span class='chord'>Am</span> lon<span class='chord'>G</span>ely</p>
\
{chorus}\
\
<p class='song show-chords'><span class='chord'>Am</span>God speed all the<span class='chord'>C</span> baker's at<span class='chord'>F</span> dawn</p>
<p class='song show-chords'>May they all<span class='chord'>C</span> cut their<span class='chord'>G</span> thumbs</p>
<p class='song show-chords'>And<span class='chord'>C</span> bleed into their<span class='chord'>F</span> buns</p>
<p class='song show-chords'>'Till they<span class='chord'>Am</span> melt<span class='chord'>G</span> away</p>
\
\
<p class='song show-chords'><span class='chord'>G</span>I'm looking in on the <span class='chord'>C</span>good life</p>
<p class='song show-chords'>I might be<span class='chord'>F</span> doomed<span class='chord'>C</span> never to<span class='chord'>G</span> find</p>
<p class='song show-chords'>Without a trust or flaming<span class='chord'>C</span> fields</p>
<p class='song show-chords'>    <span class='chord'>F</span> <span class='chord'>C</span>     <span class='chord'>G</span></p>
<p class='song show-chords'><span class='chord'>Am</span> too dumb to refine?</p>
<p class='song show-chords'>And if you'd a took to<span class='chord'>C</span> me like</p>
<p class='song show-chords'>Well<span class='chord'>F</span> I'd a<span class='chord'>C</span> danced like the<span class='chord'>F</span> queen of the<span class='chord'>C</span> eyesores</p>
<p class='song show-chords'><span class='chord'>F</span>And the rest of our<span class='chord'>C</span> lives would'a<span class='chord'>G</span> fared well</p>
{end_of_chorus}\
