## Streets of London - Ralph McTell
\
<p class='song show-chords'><span class='chord'>C</span>Have you seen the<span class='chord'>G</span> old man,<span class='chord'>Am</span> in the closed-down<span class='chord'>Em</span> market</p>
<p class='song show-chords'><span class='chord'>F</span>picking up the<span class='chord'>C</span> papers, with his<span class='chord'>D7</span> worn-out<span class='chord'>G7</span> shoes?</p>
<p class='song show-chords'><span class='chord'>C</span>In his eyes you<span class='chord'>G</span> see no pride,<span class='chord'>Am</span> and held loosely<span class='chord'>Em</span> by his side</p>
<p class='song show-chords'><span class='chord'>F</span>yesterday's<span class='chord'>C</span> papers, telling<span class='chord'>G7</span> yesterday's<span class='chord'>C</span> news</p>
\
**Chorus:**\
<p class='song show-chords'>    S<span class='chord'>F</span>o how can yo<span class='chord'>Em</span>u tell me, you'r<span class='chord'>C</span>e lo <span class='chord'>G7</span>- ne - <span class='chord'>Am</span>ly</p>
<p class='song show-chords'><span class='chord'>D7</span>  and say for<span class='chord'>D7</span> you that the sun don't<span class='chord'>G</span> shine?<span class='chord'>G7</span></p>
<p class='song show-chords'><span class='chord'>C</span>Let me take you<span class='chord'>G</span> by the hand, and<span class='chord'>Am</span> lead you through the<span class='chord'>Em</span> streets of London</p>
<p class='song show-chords'><span class='chord'>F</span>  I'll show you<span class='chord'>C</span> something, to<span class='chord'>G7</span> make you change your<span class='chord'>C</span> mind<span class='chord'>C</span></p>
\
\
Have you seen the old gal, who walks the streets of London\
dirt in her hair, and her clothes in rags?\
She's no time for talking, she just keeps right on walking\
Carrying her home, in two carrier bags\
\
{chorus}\
\
And in the all-night cafe, at a quarter past eleven\
some old man sitting there, all on his own\
Looking at the world, over the rim of his tea-cup\
Each day lasts an hour, then he wanders home alone\
\
{chorus}\
\
And have you seen the old man, outside the seaman's mission?\
His memory's fading, with those medal ribbons that he wears\
And in our winter city, the rain cries little pity\
For one more forgotten hero, and a world that doesn't care\
\
\
