name: bookdown

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
          R -e 'tinytex::install_tinytex()'
          R -e 'remotes::install_github("ratnanil/songbookdown")'

      - name: Build songfiles
        run: |
          R -e 'songbookdown::create_inputfiles()'

      - name: Build site (gitbook-html)
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
      
      - name: Build site (pdf)
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
        
      - name: Replace the edit Links
        run: R -e 'songbookdown::replace_edit_url()'

      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify (Main Page)
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir docs
          
      - name: Build site (gitbook-html)
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::html_book")'
        
      - name: Deploy to Netlify (Example Page)
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_2ID }}
        run: |
          netlify deploy --prod --dir docs
          
        
